<?php
return [
    'email_footer' => 'لطفا به این ایمیل پاسخ ندهید. این ایمیل به صورت خودکار توسط سیستم ما ارسال شده است',
    'login_message' => 'لطفا برای شروع وارد شوید',
    'text_forgot_password' => 'رمز عبورتان را فراموش کرده اید؟',
    'page_title_login' => 'ورود به پنل',
    'page_title_forgot' => 'فراموشی رمز عبور',
    'forgot_message' => 'برای دریافت رمز عبور، ایمیلتان را وارد کنید',
    "forgot_text_try_again" => "مجددا برای ورود تلاش می کنید؟",
    'text_no_notification' => "شما هیچ اعلانی ندارید",
    'text_view_all_notification' => 'مشاهده همه',
    'label_button_profile' => "پروفایل",
    'filter_dialog_title' => 'مرتب سازی و فیلتر پیشرفته',
    'there_is_no_option' => 'هیچ تنظیماتی برای این نوع ورودی وجود ندارد',
    'no' => 'خیر.',

    'text_enter_the_password' => 'رمز عبورتان را وارد کرده تا اطلاعاتتان را بازیابی کنید',
    'text_or_sign_in' => 'یا به عنوان یک کاربر دیگر وارد شوید',
    'text_default_add_new_module' => 'افزودن :module',
    'text_default_list_module' => 'لیست :module',
    'text_default_help_password' => 'حداقل5کاراکتر وارد کنید. اگه نمیخواهید تغییر کند این قسمت را خالی بگذارید ',
    'text_default_help_upload' => 'پشتیبانی از این نوع فایل ها : JPG, JPEG, PNG, GIF, BMP',
    'text_default_help_number' => 'شما فقط میتوانید عدد وارد نمایید',
    'text_default_help_email' => 'لطفا یک آدرس ایمیل صحیح وارد نمایید',
    'text_default_help_text' => 'شما فقط میتوانید حروف وارد نمایید',
    'text_default_help_url' => 'لطفا یک آدرس اینترنتی معتبر وارد نمایید',
    'text_dashboard' => 'داشبورد',
    'text_delete' => 'حذف',
    'text_prefix_option' => 'انتخاب کنید ** لطفا یک',
    'text_loading' => '...لطفا برای بار گذاری صبر کنید',

    'message_after_logout' => 'متشکریم. بعدا شما را خواهیم دید',
    'message_forgot_password' => 'لطفا صندوق ورودی یا صندوق اسپم ایمیلتان را چک کنید,ما رمز عبور جدیدتان را برایتان فرستاده ایم ',

    'page_not_found' => 'صفحه مورد نظر یافت نشد !وای ',
    'page_not_found_text' => 'ما نتوانستیم صفحه ای که به دنبالش هستید را پیدا کنیم',
    'page_not_found_tips' => '* لطفا اطمینان حاصل کنید آدرس اینترنتی وارد شده صحیح است<br/>
                * بزرگ بودن حروف درست باشد چون به بزرگ و کوچک بودن حروف حساس است/لطفا مطمئن شوید کوچک<br/>
                * شاید صفحه ای که به دنبالش هستید توسط ادمین حذف شده است<br/>
                * شما میتوانید با کلیک کردن بر روی دکمه بازگشت مرورگر به صفحه قبلی باز گردید<br/>',

    'alert_delete_selected' => 'آیا برای حذف داده های انتخاب شده مطمئن هستید؟',
    'alert_delete_selected_success' => 'حزف انتخاب شده ها با موفقیت انجام شد !',
    'alert_bulk_action_button' => 'آیا برای انجام این کار مطمئن هستید',
    'alert_action' => 'شما  :action را با موفقیت انجام دادید!',
    'alert_add_data_success' => 'داده افزوده شد !',
    'alert_add_data_failed' => 'خطا در هنگام ذخیره سازی داده !',
    'alert_update_data_success' => 'اطلاعات به روز رسانی شد !',
    'alert_update_data_failed' => 'خطا در هنگام بروزرسانی اطلاعات',
    'alert_delete_data_success' => 'حذف اطلاعات با موفقیت انجام شد !',
    'alert_want_to_logout' => 'آیا برای خروج مطمئن هستید ?',
    'alert_warning' => "وای",
    'alert_danger' => '...مشکلی پیش آمده است',
    'alert_success' => 'با موفقیت انجام شد',
    'alert_info' => 'اطلاعات',
    'alert_primary' => 'اطلاعات',
    'alert_session_expired' => 'لطفا مجددا وارد شوید.نشست شما منقضی شده است ',
    'alert_password_wrong' => 'متاسفانه رمز عبور شما اشتباه است',
    'alert_required' => 'لطفا مطمئن شوید تمام اطلاعات خواسته شده را به درستی وارد کرده اید',
    'alert_error_ajax' => 'متاسفانه مشکلی پیش آمده است . ما به زودی آن را بر طرف خواهیم کرد',
    'alert_validation_error' => 'لطفا فرم را به درستی پر نمایید : :error',

    'add_data_page_title' => 'افزودن :module',
    'edit_data_page_title' => 'اصلاح :module',
    'detail_data_page_title' => 'جزییات :module',

    'default_module_description' => 'لیست داده',

    'delete_description_confirm' => "شما قادر به بازگردانی این داده نخواهید بود",
    'delete_title_confirm' => "آیا مطمئن هستید؟",

    'action_show_data' => 'مشاهده داده',
    'action_add_data' => 'افزودن داده',
    'action_delete_selected' => 'حزف انتخاب شده',

    'action_label' => 'عمل',
    'action_detail_data' => 'جزییات داده',
    'action_edit_data' => 'اصلاح داده',
    'action_delete_data' => 'حذف',

    'button_cancel' => 'لغو',
    'button_add' => 'افزودن داده',
    'button_edit' => 'اصلاح داده',
    'button_back' => 'بازگشت',
    'button_save' => 'ذخیره',
    'button_save_more' => 'ذخیره و افزودن داده ای دیگر',
    'button_import' => 'وارد کردن داده',
    'button_export' => 'خروجی گرفتن از داده',
    'button_filter' => 'مرتب سازی و فیلتر',
    'button_close' => 'بستن',
    'button_submit' => 'ثبت',
    'button_logout' => 'خروج',
    'button_sign_in' => 'ورود',
    'button_selected_action' => 'عمل دسته جمعی',
    'button_download_file' => 'دانلود فایل',
    'button_reset' => 'ریست',
    'button_add_to_table' => 'افزودن به جدول',

    'export_dialog_title' => "خروجی گرفتن از دیتا",
    'export_dialog_filename' => 'نام فایل',
    'export_dialog_help_filename' => 'شما میتوانید هر طور که میخواهید نام فایل را تغییر دهید',
    'export_dialog_maxdata' => "بیشترین داده",
    'export_dialog_help_maxdata' => 'داده به ازای هر بار خروجی گرفتن 100,000حداقل یک و حداکثر ',
    'export_dialog_columns' => 'ستون ها',
    'export_dialog_format_export' => 'فرمت خروجی',
    'export_dialog_show_advanced' => 'مشاهده خروجی گرفتن پیشرفته',
    'export_dialog_page_size' => 'اندازه صفحه',
    'export_dialog_set_default' => 'انتخاب به عنوان اندازه صفحه پیشفرض',
    'export_dialog_page_orientation' => 'جهت صفحه',

    'import_page_title' => 'وارد کردن داده به :module',
    'dashboard_default_text' => 'به داشبورد :appname خوش آمدید',
    'form_back_to_list' => 'بازگشت به لیست داده های:module',
    'not_logged_in' => '!شما وارد نشده اید',
    'menu_navigation' => "ناوبری",
    'table_data_not_found' => "داده ای در دسترس نیست",
    "notice_delete_file_upload" => "* اگر میخواهید فایلی دیگر آپلود کنید لطفا اول فایل را پاک نمایید",
    "file_broken" => "وای  ظاهرا فایل کامل نیست لطفا فایل را حزف نموده و مجددا آپلود نمایید",

    'denied_access' => 'متاسفانه شما اجازه دسترسی به این بخش را ندارید',
    'denied_update' => 'شما اجازه بروزرسانی این داده را ندارید',
    'denied_create' => 'شما اجازه ساخت این نوع داده را ندارید',
    'denied_delete' => 'شما اجازه حزف این نوع داده را ندارید',

    'user_image' => 'تصویر کاربر',
    'online' => 'آنلاین',
    'controller_route_404' => 'Controller / Route یافت نشد',
    'home' => 'خانه',
    'Notificactions' => 'اعلان ها',
    'Privileges' => 'امتیازات',
    'Privileges_Roles' => 'امتیازات نقش ها',
    'Add_New_Privilege' => 'افزودن امتیاز',
    'List_Privilege' => 'لیست امتیاز',
    'add_user' => 'افزودن کاربر',
    'List_users' => 'لیست کاربران',
    'Menu_Management' => 'مدیریت منو',
    'menu_filemanager' => 'مدیریت فایل',
    'Add_New_Setting' => 'افزودن تنظیمات جدید',
    'Add_New_Module' => 'افزودن ماژول جدید',
    'List_Module' => 'لیست ماژول ها',
    'Add_New_Statistic' => 'افزودن آمار جدید',
    'List_Statistic' => 'لیست آمار',
    'Add_New_API' => 'جدید API افزودن',
    'API_Generator' => 'API ساز',
    'Statistic_Builder' => 'آمار ساز',
    'Module_Generator' => 'ماژول ساز',
    'settings' => 'تنظیمات',
    'Users_Management' => 'مدیریت کاربران',
    'list_API' => 'لیست API (مستندات)',
    'Generate_Screet_Key' => 'ساخت Secret Key',
    'Add_New_Email' => 'افزودن ایمیل جدید',
    'List_Email_Template' => 'لیست قالب های ایمیل',
    'Email_Templates' => 'قالب های ایمیل',
    'Log_User_Access' => 'کارهای انجام شده کاربران',
    'SUPERADMIN' => 'ادمین اصلی',

    'click_here' => 'کلیک کنید',

    /*
 * this is for html direction to use in html and css classes like :
 * pull-left , pull-right , text-right ...
 * to make it easy to use the the view for rtl langs .
 * unless your language use right-to-left direction , you should keep it as it is :
 */
    'right' => 'right',
    'left' => 'left',

    'all_rights_reserved' => 'تمام حقوق محافظت شده است',
    'copyright' => 'کپی رایت',
    'powered_by' => 'قدرت گرفته از',

    'notification_you_have' => 'شما دارید',
    'notification_notification' => 'اعلان ها',
    'notification_new' => 'شما یک اعلان جدید دارید',

    'login_register_style' => 'ورود به روش ثبت نام',
    'email_setting' => 'تنظیمات ایمیل',
    'application_setting' => 'تنظیمات نرم افزار',

    // table filter & sort
    'filter_select_operator_type' => 'انتخاب عمل',
    'filter_ascending' => 'صعودی',
    'filter_descending' => 'نزولی',
    'filter_equal_to' => '=(برابر بودن)',
    'filter_like' => 'مشابه بودن',
    'filter_not_like' => 'مشابه نبودن ',
    'filter_greater_than_or_equal' => '>= (بزرگتر یا مساوی)',
    'filter_less_than_or_equal' => '<= (کوچکتر یا مساوی)',
    'filter_less_than' => '< (کوچکتر از)',
    'filter_greater_than' => '> (بزرگتر از)',
    'filter_not_equal_to' => '!= (برابر نبودن)',
    'filter_in' => 'در',
    'filter_not_in' => 'نبودن در',
    'filter_between' => 'مابین',
    'filter_sort_ascending' => 'مرتب کردن صعودی',
    'filter_sort_descending' => 'مرتب کردن نزولی',
    'filter_eg' => 'برای مثال',
    'filter_lorem_ipsum' => 'لورم ایپسام',
    'filter_lorem_ipsum_dolor_sit' => 'لورم ایپسام متن ساختگی است',
    'filter_search' => 'جستجو',
    'filter_from' => 'از',
    'filter_to' => 'تا',
    'filter_sorting' => 'مرتب سازی',

    // confirmation
    'confirmation_yes' => '!بله',
    'confirmation_no' => 'خیر',

    //filemanager
    'chose_an_image' => 'یک تصویر انتخاب نمایید ',
    'chose_an_file' => 'یک فایل انتخاب نمایید ',

    //action confirmation
    'confirmation_title' => 'تاییه',
    'confirmation_text' => 'آیا برای انجام این کار مطمئن هستید؟',
    'confirmButtonText' => 'بله',

    //datamodal
    'datamodal_select' => 'انتخاب',
    'datamodal_search_and_enter' => '...متن جستجو را وارد کرده و اینتر را بزنید',
    'datamodal_enter_to_search' => 'برای جستجو اینتر را بزنید',
    'datamodal_browse_data' => 'مشاهده داده',
    'datamodal_browse_file' => 'مشاهده فایل',

    //child
    'table_detail' => 'جزییات جدول',
    'your_file_size_is_too_big' => 'حجم فایل شما بسیار سنگین است',
    'save_changes' => 'ذخیره تغییرات',
    'please_complete_the_form' => 'لطفا فرم را تکمیل نمایید',
    'this_field_is_required' => 'تکمیل این فیلد اجباری است',
    'text_form' => 'فرم',
    "your_file_extension_is_not_allowed " => "نوع فایل شما مجاز نیست",

    'toggle_navigation' => "Toggle navigation",
    'information' => "Information",

];