<?php
return [
    'email_footer'               => 'Do not reply any email to this email address. This email sent automatically by our system. ',
    'login_message'              => 'Please login to start your session',
    'text_forgot_password'       => 'Forgot the password ?',
    'page_title_login'           => 'Login Panel',
    'page_title_forgot'          => 'Forgot Password',
    'forgot_message'             => 'Enter your email address, to request password',
    "forgot_text_try_again"      => "Try login again ?",
    'text_no_notification'       => "You have 0 notifications",
    'text_view_all_notification' => 'View All',
    'label_button_profile'       => "Profile",
    'filter_dialog_title'        => 'Advanced Sort & Filter',

    'text_enter_the_password'     => 'Enter your password to retrieve your session',
    'text_or_sign_in'             => 'Or sign in as a different user',
    'text_default_add_new_module' => 'Add New :module',
    'text_default_list_module'    => 'List :module',
    'text_default_help_password'  => 'Minimum 5 characters. Please leave empty if you did not change the password.',
    'text_default_help_upload'    => 'File types support : JPG, JPEG, PNG, GIF, BMP',
    'text_default_help_number'    => 'You can only enter the number only',
    'text_default_help_email'     => 'Please enter a valid email address',
    'text_default_help_text'      => 'You can only enter the letter only',
    'text_default_help_url'       => 'Please enter a valid URL',
    'text_dashboard'              => 'Dashboard',
    'text_prefix_option'          => '** Please select a',
    'text_loading'                => 'Please wait loading...',

    'message_after_logout'    => 'Thank You, See You Later !',
    'message_forgot_password' => 'We have sent new password to your email, check inbox or spambox !',

    'page_not_found'      => 'Oops! Page Not Found',
    'page_not_found_text' => 'We are unable search the page that you are looking for.',
    'page_not_found_tips' => '* Please make sure the URL is correct<br/>
                * Please make sure the font capitalizing is correct because case sensitive<br/>
                * Maybe the page that you are looking for has been deleted by Admin<br/>
                * You can go back by click Back Button at browser<br/>',

    'log_try_view'            => 'Try view the data :name at :module',
    'log_try_edit'            => 'Try edit the data :name at :module',
    'log_try_add'             => 'Try add data at :module',
    'log_try_add_save'        => 'Try add the data :name data at :module',
    'log_try_delete'          => 'Try delete the :name data at :module',
    'log_try_delete_selected' => 'Try delete selected at :module',
    'log_try_delete_image'    => 'Try delete the image of :name data at :module',
    'log_try_update'          => 'Try update the :name data at :module',
    'log_add'                 => 'Add New Data :name at :module',
    'log_update'              => 'Update data :name at :module',
    'log_delete'              => 'Delete data :name at :module',
    'log_delete_image'        => 'Delete the image of :name at :module',
    'log_login'               => ':email login with IP Address :ip',
    'log_forgot'              => 'Someone with IP :ip request a password for :email',
    'log_logout'              => ':email logout',

    'alert_delete_selected'         => 'Are you sure want to delete all selected data ?',
    'alert_delete_selected_success' => 'Delete selected success !',
    'alert_action'                  => 'You have :action successfully !',
    'alert_add_data_success'        => 'The data has been added !',
    'alert_add_data_failed'         => 'Failed to save the data !',
    'alert_update_data_success'     => 'The data has been updated !',
    'alert_update_data_failed'      => 'Failed to update the data',
    'alert_delete_data_success'     => 'Delete the data success !',
    'alert_want_to_logout'          => 'Do you want to logout ?',
    'alert_warning'                 => "Oops",
    'alert_danger'                  => 'Something went wrong ....',
    'alert_success'                 => 'Wow, good job...',
    'alert_info'                    => 'Information',
    'alert_primary'                 => 'Information',
    'alert_session_expired'         => 'Your session was expired, please login again !',
    'alert_password_wrong'          => 'Sorry your password is wrong !',
    'alert_required'                => 'Please make sure to fill out all the required fields correctly',
    'alert_error_ajax'              => 'Okay, It is embarasing, something went wrong, we will fix it soon !',
    'alert_validation_error'        => 'Please fill out the form correctly : :error',

    'add_data_page_title'    => 'Add :module',
    'edit_data_page_title'   => 'Edit :module',
    'detail_data_page_title' => 'Detail :module',

    'default_module_description' => 'Data List',

    'delete_description_confirm' => "You will not be able to recover this record data!",
    'delete_title_confirm'       => "Are you sure ?",


    'action_show_data'       => 'Show Data',
    'action_add_data'        => 'Add Data',
    'action_delete_selected' => 'Delete Selected',

    'action_label'       => 'Action',
    'action_detail_data' => 'Detail Data',
    'action_edit_data'   => 'Edit Data',
    'action_delete_data' => 'Delete',


    'button_cancel'          => 'Cancel',
    'button_add'             => 'Add Data',
    'button_edit'            => 'Edit Data',
    'button_back'            => 'Back',
    'button_save'            => 'Save',
    'button_save_more'       => 'Save & Add More',
    'button_import'          => 'Import Data',
    'button_export'          => 'Export Data',
    'button_filter'          => 'Sort & Filter',
    'button_close'           => 'Close',
    'button_submit'          => 'Submit',
    'button_logout'          => 'Logout',
    'button_sign_in'         => 'Sign In',
    'button_selected_action' => 'Bulk Actions',
    'button_download_file'   => 'Download file',
    'button_reset'           => 'Reset',

    'export_dialog_title'            => "Export Data",
    'export_dialog_filename'         => 'File Name',
    'export_dialog_help_filename'    => 'You can rename the filename according to your whises',
    'export_dialog_maxdata'          => "Max Data",
    'export_dialog_help_maxdata'     => 'Minimum 1 and maximum 100,000 rows per export session',
    'export_dialog_columns'          => 'Columns',
    'export_dialog_format_export'    => 'Format Export',
    'export_dialog_show_advanced'    => 'Show Advanced Export',
    'export_dialog_page_size'        => 'Page Size',
    'export_dialog_set_default'      => 'Set As Default Paper Size',
    'export_dialog_page_orientation' => 'Page Orientation',

    'import_page_title'         => 'Import Data :module',
    'dashboard_default_text'    => 'Welcome to the dashboard of :appname',
    'form_back_to_list'         => 'Back To List Data :module',
    'not_logged_in'             => 'You are not logged in !',
    'menu_navigation'           => "Navigation",
    'table_data_not_found'      => "No Data Avaliable",
    "notice_delete_file_upload" => "* If you want to upload other file, please first delete the file.",
    "file_broken"               => "Oops looks like File was Broken !. Click Delete and Re-Upload.",

    'denied_access' => 'Sorry you do not have privilege to access this area !',
    'denied_update' => 'Sorry you do not have privilege to update the data !',
    'denied_create' => 'Sorry you do not have privilege to create the data !',
    'denied_delete' => 'Sorry you do not have privilege to delete the data !',

    'user_image'           => 'User Image',
    'online'               => 'Online',
    'controller_route_404' => 'Controller / Route Not Found',
    'home'                 => 'Home',

    'Privileges_Roles'    => 'Privileges Roles',
    'Add_New_Privilege'   => 'Add New Privilege',
    'List_Privilege'      => 'List Privilege',
    'add_user'            => 'Add User',
    'List_users'          => 'List Users',
    'Menu_Management'     => 'Menu Management',
    'Add_New_Setting'     => 'Add New Setting',
    'Add_New_Module'      => 'Add New Module',
    'List_Module'         => 'List Module',
    'Add_New_Statistic'   => 'Add New Statistic',
    'List_Statistic'      => 'List Statistic',
    'Add_New_API'         => 'Add New API',
    'API_Generator'       => 'API Generator',
    'Statistic_Builder'   => 'Statistic Builder',
    'Module_Generator'    => 'Module Generator',
    'settings'            => 'Settings',
    'Users_Management'    => 'Users Management',
    'list_API'            => 'List API (Documentation)',
    'Generate_Screet_Key' => 'Generate Secret Key',
    'Add_New_Email'       => 'Add New Email',
    'List_Email_Template' => 'List Email Template',
    'Email_Templates'     => 'Email Templates',
    'Log_User_Access'     => 'Log User Access',
    'SUPERADMIN'          => 'SUPERADMIN',

    'click_here' => 'Click here',

    /*
     * this is for html direction to use in html and css classes like :
     * pull-left , pull-right , text-right ...
     * to make it easy to use the the view for rtl langs .
     * unless your language use right-to-left direction , you should keep it as it is :
     */
    'right'      => 'right',
    'left'       => 'left',

    'all_rights_reserved' => 'All Rights Reserved',
    'copyright'           => 'Copyright',
    'powered_by'          => 'Powered by',

    'notification_you_have'     => 'You Have',
    'notification_notification' => 'Notifications',
    'notification_new'          => 'You have a new notification !',

    'login_register_style'         => 'Login Register Style',
    'email_setting'                => 'Email Setting',
    'application_setting'          => 'Application Setting',

    // table filter & sort 
    'filter_select_operator_type'  => 'Select Operator Type',
    'filter_ascending'             => 'ASCENDING',
    'filter_descending'            => 'DESCENDING',
    'filter_equal_to'              => '=(Equal to)',
    'filter_like'                  => 'LIKE',
    'filter_not_like'              => 'NOT LIKE',
    'filter_greater_than_or_equal' => '>= (Greater Than or Equal)',
    'filter_less_than_or_equal'    => '<= (Less Than or Equal)',
    'filter_less_than'             => '< (Less Than)',
    'filter_greater_than'          => '> (Greater Than)',
    'filter_not_equal_to'          => '!= (Not Equal to)',
    'filter_in'                    => 'IN',
    'filter_not_in'                => 'NOT IN',
    'filter_between'               => 'BETWEEN',
    'filter_sort_ascending'        => 'Sort ascending',
    'filter_sort_descending'       => 'Sort Descending',
    'filter_eg'                    => 'e.g',
    'filter_lorem_ipsum'           => 'Lorem ipsum',
    'filter_lorem_ipsum_dolor_sit' => ' Lorem,Ipsum,Dolor Sit',
    'filter_search'                => 'Search',
    'filter_from'                  => 'from',
    'filter_to'                    => 'to',

    // confirmation
    'confirmation_yes'             => 'Yes!',
    'confirmation_no'              => 'No',

    //filemanager
    'chose_an_image'               => 'Choose an image ',
    'chose_an_file'                => 'Choose an file ',

];
