<?php
return [
    'email_footer' => 'Bu e-posta adresine herhangi bir e-posta cevap vermeyin. Bu e-posta sistemimiz tarafından otomatik olarak gönderilir. ',
    'login_message' => 'Oturumu başlatmak için giriş yapın',
    'text_forgot_password' => 'Şifreni mi unuttun?',
    'page_title_login' => 'Giriş Paneli',
    'page_title_forgot' => 'Şifremi Unuttum',
    'forgot_message' => 'Parola isteğinde bulunmak için e-posta adresinizi girin',
    "forgot_text_try_again" => "Tekrar giriş yapınız ?",
    'text_no_notification' => "Bildiriminiz yok",
    'text_view_all_notification' => 'Tümünü Göster',
    'label_button_profile' => "Profil",
    'filter_dialog_title' => 'Gelişmiş Filtreleme & Sıralama',
    'there_is_no_option' => 'Bu girdi türü için herhangi bir seçenek ayarı yok',
    'no' => 'Hayır.',

    'text_enter_the_password' => 'Oturum açmak için parolanızı girin',
    'text_or_sign_in' => 'Ya da farklı bir kullanıcı olarak oturum',
    'text_default_add_new_module' => 'Yeni Ekle :module',
    'text_default_list_module' => 'Listele :module',
    'text_default_help_password' => 'En az 5 karakter. Eğer şifreyi değiştirmediyseniz boş bırakın.',
    'text_default_help_upload' => 'Desteklenen soya türleri : JPG, JPEG, PNG, GIF, BMP',
    'text_default_help_number' => 'Sadece numara girin',
    'text_default_help_email' => 'Lütfen geçerli bir e-posta adresini girin',
    'text_default_help_text' => 'Sadece tek harf girebilirsiniz',
    'text_default_help_url' => 'Lütfen geçerli bir URL girin',
    'text_dashboard' => 'Pano',
    'text_delete' => 'Sil',
    'text_prefix_option' => '** Lütfen seçiniz ',
    'text_loading' => 'Yükleniyor lütfen bekleyiniz...',

    'message_after_logout' => 'Teşekkür Ederim, Sonra Görüşürüz !',
    'message_forgot_password' => 'E-postanıza yeni şifre gönderdik, gelen kutusu veya spam kutunuzu kontrol edin !',

    'page_not_found' => 'Haydaa! Sayfa bulunamadı.',
    'page_not_found_text' => 'Aradığınız sayfayı bulamıyoruz. Teknik çalışmalarımız sürüyor. üzgünüm :( ',
    'page_not_found_tips' => '* Lütfen URLnin doğru olduğundan emin olun<br/>
                * font yolunun doğru olmasına dikkat edin, çünkü büyük / küçük harf duyarlı<br/>
                * Belki aradığınız sayfa Admin tarafından silindi<br/>
                * Geri  Düğmesine tıklayın <br/>',

    'log_try_view' => 'Verileri görüntülemeyi denedi :name / :module',
    'log_try_edit' => 'Verileri düzenlemeyi denedi :name at :module',
    'log_try_add' => 'Veri eklemeyi denedi :module',
    'log_try_add_save' => 'Veri eklemeyi denedi :name / :module',
    'log_try_delete' => 'Veri silmem denendi :name verisi ile ( :module ) ',
    'log_try_delete_selected' => 'Seçileni silme denendi :module',
    'log_try_delete_image' => 'Resim silme denendi :name / :module',
    'log_try_update' => 'Veri güncelleme denendi :name / :module',
    'log_add' => 'Veri Eklendi :name / :module',
    'log_update' => 'Veri Güncellendi :name / :module',
    'log_delete' => 'Veri Silindi :name / :module',
    'log_delete_image' => 'Resim silindi :name / :module',
    'log_login' => ':email giriş yaptı. ip adresi :ip',
    'log_forgot' => 'IP adresi(:ip) olan birisi :email için şifre istedi',
    'log_logout' => ':email çıkış yaptı',

    'alert_delete_selected' => 'Seçilen tüm verileri silmek istiyor musun ?',
    'alert_delete_selected_success' => 'Seçilenler silindi !',
    'alert_bulk_action_button' => 'Emin misin',
    'alert_action' => ':action Başarılı !',
    'alert_add_data_success' => 'Veri eklendi !',
    'alert_add_data_failed' => 'Veri ekleme başarısız !',
    'alert_update_data_success' => 'Veri güncellendi !',
    'alert_update_data_failed' => 'Veri güncelleme başarısız',
    'alert_delete_data_success' => 'Veri silme başarılı !',
    'alert_want_to_logout' => 'Çıkış yapmak istiyor musunuz ?',
    'alert_warning' => "Uyarı ! ",
    'alert_danger' => 'Bir şeyler ters gitti ....',
    'alert_success' => 'Harika , iyi iş...',
    'alert_info' => 'Bilgi',
    'alert_primary' => 'Bilgi',
    'alert_session_expired' => 'Oturum Süreniz Dolmuş,Lütfen Tekrar giriş yapınız !',
    'alert_password_wrong' => 'Üzgünüm parolanız yanlış !',
    'alert_required' => 'Lütfen gerekli tüm alanları doldurduğunuzdan emin olun',
    'alert_error_ajax' => 'Bir şeyler yanlış gitti, yakında düzeltiriz!',
    'alert_validation_error' => 'Lütfen doğru formu doldurun : :error',

    'add_data_page_title' => ':module | Ekle ',
    'edit_data_page_title' => ':module | Düzenle  ',
    'detail_data_page_title' => ':module | Detay',

    'default_module_description' => 'Kayıt listesi',

    'delete_description_confirm' => "Bu veriyi kurtarmak mümkün olmayacak!",
    'delete_title_confirm' => "Silmek istediğinizden emin misiniz ?",

    'action_show_data' => 'Veriler',
    'action_add_data' => 'Ekle',
    'action_delete_selected' => 'Seçileni sil',

    'action_label' => 'İşlemler',
    'action_detail_data' => 'Detay',
    'action_edit_data' => 'Düzenle',
    'action_delete_data' => 'Sil',

    'button_cancel' => 'İptal',
    'button_add' => 'Ekle',
    'button_edit' => 'Düzenle',
    'button_back' => 'Geri',
    'button_save' => 'Kaydet',
    'button_save_more' => 'Kaydet & Yeni',
    'button_import' => 'İçe Aktar',
    'button_export' => 'Dışa Aktar',
    'button_filter' => 'Sıralama & Filtreleme',
    'button_close' => 'Kapat',
    'button_submit' => 'Gönder',
    'button_logout' => 'Çıkış',
    'button_sign_in' => 'Giriş',
    'button_selected_action' => 'Toplu İşlem',
    'button_download_file' => 'Dosyayı indir',
    'button_reset' => 'Sıfırla',
    'button_add_to_table' => 'Ekle',

    'export_dialog_title' => "Dışa Aktar",
    'export_dialog_filename' => 'Dosya Adı',
    'export_dialog_help_filename' => 'İsteğinize göre dosya adını yeniden adlandırabilirsiniz',
    'export_dialog_maxdata' => "Maksimum",
    'export_dialog_help_maxdata' => 'En az 1 ve en fazla 100.000 satır ',
    'export_dialog_columns' => 'Sutün',
    'export_dialog_format_export' => 'Dışa Aktarma Sıfırla',
    'export_dialog_show_advanced' => 'Gelişmiş Dışa Aktarma',
    'export_dialog_page_size' => 'Sayfa Boyutu',
    'export_dialog_set_default' => 'Varsayılan Kağıt Boyutu Olarak Ayarlayın',
    'export_dialog_page_orientation' => 'Sayfa Yönlendirme',

    'import_page_title' => 'İçer Aktar :module',
    'dashboard_default_text' => ':appname panosuna hoş geldiniz',
    'form_back_to_list' => 'Veri Listesi (:module)',
    'not_logged_in' => 'Giriş yapmadınız !',
    'menu_navigation' => "Menü",
    'table_data_not_found' => "Veri yok",
    "notice_delete_file_upload" => "* Eğer başka bir dosya yüklemek istiyorsanız, lütfen  önce  var olan dosyayı siliniz.",
    "file_broken" => "Hata! Dosya bozulmuş gibi görünüyor! Sil ve Yeniden Yükle'yi tıklayın.",

    'denied_access' => 'Üzgünüm bu bölgeye erişmek için yetkiniz yok!',
    'denied_update' => 'Maalesef verileri güncellemek için yetkiniz yok!',
    'denied_create' => 'Maalesef verileri oluşturmak için yetkiniz yok!',
    'denied_delete' => 'Maalesef verileri silmek için yetikiniz yok!',

    'user_image' => 'User Image',
    'online' => 'Çevrimiçi',
    'controller_route_404' => 'Controller / Route Sayfa bulunamadı',
    'home' => 'Anasayfa',
    'Notifications' => 'Notifications',
    'Privileges' => 'Privileges',
    'Privileges_Roles' => 'Yetki Rolleri',
    'Add_New_Privilege' => 'Rol Ekle',
    'List_Privilege' => 'Roller',
    'add_user' => 'Kullanıcı Ekle',
    'List_users' => 'Kullanıcılar',
    'Menu_Management' => 'Menü Yönetimi',
    'Add_New_Setting' => 'Yeni Ayar ekle',
    'Add_New_Module' => 'Yeni Modül Ekle',
    'List_Module' => 'Modüller',
    'Add_New_Statistic' => 'İstatistik Ekle',
    'List_Statistic' => 'İstatistikler',
    'Add_New_API' => 'API Ekle',
    'API_Generator' => 'API Oluşturucu',
    'Statistic_Builder' => 'İstatistik Oluşturucu',
    'Module_Generator' => 'Modül Oluşturucu',
    'settings' => 'Ayarlar',
    'Users_Management' => 'Kullanıcı Yönetimi',
    'list_API' => 'API Listesi (Dökümantasyon)',
    'Generate_Screet_Key' => 'Güvenli Anahtar Oluşturma',
    'Add_New_Email' => 'Yeni E-Posta Ekle',
    'List_Email_Template' => 'E-Posta Şablonu Listesi',
    'Email_Templates' => 'E-Posta Şablonları',
    'Log_User_Access' => 'Kullanıcı Günlük Erişimi',
    'SUPERADMIN' => 'SUPERADMIN',

    'click_here' => 'Buraya Tıklayınız',

    /*
     * this is for html direction to use in html and css classes like :
     * pull-left , pull-right , text-right ...
     * to make it easy to use the the view for rtl langs .
     * unless your language use right-to-left direction , you should keep it as it is :
     */
    'right' => 'right',
    'left' => 'left',

    'all_rights_reserved' => 'Tüm Hakları Saklıdır',
    'copyright' => 'Copyright',
    'powered_by' => 'Powered by',

    'notification_you_have' => '',
    'notification_notification' => 'bildirimin var',
    'notification_new' => 'Yeni bildirimin var!',

    'login_register_style' => 'Kayıt Sayfası Stili',
    'email_setting' => 'Email Ayarları',
    'application_setting' => 'Uygulama Ayarları',

    // table filter & sort 
    'filter_select_operator_type' => 'Karşılaştırma Türü Seçiniz',
    'filter_ascending' => 'ARTAN',
    'filter_descending' => 'AZALAN',
    'filter_equal_to' => '=(Eşittir)',
    'filter_like' => 'Benzer',
    'filter_not_like' => 'Benzer Değil',
    'filter_greater_than_or_equal' => '>>= (Büyük veya Eşittir)',
    'filter_less_than_or_equal' => '<= (Küçük veya Eşittir)',
    'filter_less_than' => '< (Küçüktür)',
    'filter_greater_than' => '> (Büyüktür)',
    'filter_not_equal_to' => '!= (Eşit Değil)',
    'filter_in' => 'İçeriyorsa',
    'filter_not_in' => 'İçermiyorsa',
    'filter_between' => 'Arasında',
    'filter_sort_ascending' => 'Artan Sıralama',
    'filter_sort_descending' => 'Azalan Sıralama',
    'filter_eg' => 'örnek ',
    'filter_lorem_ipsum' => 'Lorem ipsum',
    'filter_lorem_ipsum_dolor_sit' => 'Lorem,Ipsum,Dolor Sit',
    'filter_search' => 'Ara',
    'filter_from' => 'from',
    'filter_to' => 'Için',
    'filter_sorting' => 'Sıralama',
    // confirmation
    'confirmation_yes' => 'Evet',
    'confirmation_no' => 'Hayır',

    //filemanager
    'chose_an_image' => 'Resim Seçiniz',
    'chose_an_file' => 'Dosya Seçiniz',

    //action confirmation
    'confirmation_title' => 'Onaylama',
    'confirmation_text' => 'Bu işlemi yapmak istediğinizden emin misiniz?',
    'confirmButtonText' => 'Evet',

    // privilege
    'privileges_name' => 'Yetki ismi',
    'set_as_superadmin' => 'Süper Yönetici olarak ayarla',
    'privileges_super_admin' => 'Süper Yönetici',
    'privileges_standart_user' => 'Standart',
    'privileges_ID' => 'NO',
    'chose_theme_color_select' => 'Tema rengini seçiniz',
    'chose_theme_color' => 'Tema ',
    'privileges_configuration' => 'Yetki ayarları',
    'privileges_module_list_no' => 'No.',
    'privileges_module_list_mod_names' => 'Modül',
    'privileges_module_list_view' => 'Görüntüleme',
    'privileges_module_list_create' => 'Ekleme',
    'privileges_module_list_read' => 'Okuma',
    'privileges_module_list_update' => 'Güncelleme',
    'privileges_module_list_delete' => 'Silme',

    //datamodal
    'datamodal_select' => 'Seç',
    'datamodal_search_and_enter' => 'Aramak için yazın ve enter tuşuna basın..',
    'datamodal_enter_to_search' => 'Aramak için Enter tuşuna basınız',
    'datamodal_browse_data' => 'Gözat',
    'datamodal_browse_file' => 'Dosyaya Gözat',

    //child 
    'table_detail' => 'Tablo ',
    'your_file_size_is_too_big' => 'Dosya boyutu büyük.',
    'save_changes' => 'Değişikleri Kaydet',
    'please_complete_the_form' => 'Lütfen formu doldurun !',
    'this_field_is_required' => 'Bu alan zorunludur',
    'text_form' => 'Form',
    "your_file_extension_is_not_allowed " => "izin verilmeyen dosya türü !",

];
