<?php
return [
    'email_footer' => 'Μην απαντάτε σε αυτό το email. Αυτό είναι ένα αυτοματοποιημένο μήνυμα.',
    'login_message' => 'Εισέλθετε για να ξεκινήσετε.',
    'text_forgot_password' => 'Ξεχάσατε τον κωδικό σας;',
    'page_title_login' => 'Σελίδα εισόδου',
    'page_title_forgot' => 'Ξέχασα τον κωδικό',
    'forgot_message' => 'Εισάγετε το email σας, για να κάνετε ανναέωση του κωδικού σας',
    "forgot_text_try_again" => "Επαναδοκιμή εισόδου;",
    'text_no_notification' => "Έχετε 0 ειδοποιήσεις",
    'text_view_all_notification' => 'Προβολή όλων',
    'label_button_profile' => "Προφίλ",
    'filter_dialog_title' => 'Σορτάρισμα & Φιλτράρισμα',
    'there_is_no_option' => 'Δεν υπάρχουν επιλογές για αυτό το inputType',
    'no' => 'Όχι.',

    'text_enter_the_password' => 'Εισάγετε τον κωδικό σας για να συνεχίσετε',
    'text_or_sign_in' => 'Ή εισέλθετε ως άλλος χρήστης',
    'text_default_add_new_module' => 'Δημιουργία :module',
    'text_default_list_module' => 'Λίστα :module',
    'text_default_help_password' => 'Ελάχιστο 5 χαρακτήρες. Αφήστε το άδειο για να μην αλλάξει ο κωδικός.',
    'text_default_help_upload' => 'Υποστηριζόμενοι τύποι εικόνας : JPG, JPEG, PNG, GIF, BMP',
    'text_default_help_number' => 'Μπορείτε να εισάγετε μόνο νούμερα',
    'text_default_help_email' => 'Παρακαλώ συμπληρώστε ένα έγκυρο email',
    'text_default_help_text' => 'Μπορείτε να εισάγετε μόνο γράμματα',
    'text_default_help_url' => 'Παρακαλώ συμπληρώστε ένα έγκυρο URL',
    'text_dashboard' => 'Κεντρική Οθόνη',
    'text_delete' => 'Διαγραφή',
    'text_prefix_option' => '** Παρακαλώ επιλέξτε',
    'text_loading' => 'Φόρτωση...',

    'message_after_logout' => 'Ευχαριστούμε, Εις το επανιδείν!',
    'message_forgot_password' => 'Σας έχουμε αποστείλει email, παρακαλώ ελέγξτε τα εισερχόμενα και τα ανεπιθύμητα σας.',

    'page_not_found' => 'Ωχ! Η σελίδα δεν βρέθηκε',
    'page_not_found_text' => 'Δεν μπορέσαμε να βρούμε την σελίδα που ψάχνετε.',
    'page_not_found_tips' => '* Σιγουρευτείτε πως το URL είναι σωστό<br/>
                * μικρά και ΚΕΦΑΛΑΙΑ παίζουν ρόλο<br/>
                * Ίσως η σελίδα που ψάχνετε έχει διαγραφεί από τον διαχειριστή<br/>
                * Μπορείτε να πάτε πίσω πατώντας το "πίσω" στον φυλλομετρητή σας<br/>',

    'alert_delete_selected' => 'Είστε σίγουρος/η πως θέλετε να διεγράψετε όλα τα επιλεγμένα στοιχεία;',
    'alert_delete_selected_success' => 'Επιτυχής διαγραφή επιλεγμένων!',
    'alert_bulk_action_button' => 'Σίγουρα θέλετε να',
    'alert_action' => 'Επιτυχής :action!',
    'alert_add_data_success' => 'Η εγγραφή έγινε!',
    'alert_add_data_failed' => 'Η εγγραφή απέτυχε!',
    'alert_update_data_success' => 'Το στοιχείο ανανεώθηκε!',
    'alert_update_data_failed' => 'Η ανανέωση απέτυχε!',
    'alert_delete_data_success' => 'Η διαγραφή πέτυχε!',
    'alert_want_to_logout' => 'Θέλετε να εξέλθετε;',
    'alert_warning' => "Ωχ",
    'alert_danger' => 'Κάτι πήγε στραβά ....',
    'alert_success' => 'Μπράβο, καλή δουλειά...',
    'alert_info' => 'Πληροφορία',
    'alert_primary' => 'Πληροφορία',
    'alert_session_expired' => 'Η σύνδεση σας έληξε, παρακαλώ συνδεθείτε ξανά!',
    'alert_password_wrong' => 'Λάθος κωδικός!',
    'alert_required' => 'Συμπληρώστε σωστά όλα τα απαιτούμενα πεδία',
    'alert_error_ajax' => 'Σφάλμα, παρακαλώ ενημερώστε τον διαχειριστή!',
    'alert_validation_error' => 'Συμπληρώστε σωστά την φόρμα: :error',
    'alert_select_a_data' => 'Επιλέξτε τουλάχιστον ένα στοιχείο!',

    'add_data_page_title' => 'Προσθήκη :module',
    'edit_data_page_title' => 'Επεξεργασία :module',
    'detail_data_page_title' => 'Λεπτομέρειες :module',

    'default_module_description' => 'Λίστα Δεδομένων',

    'delete_description_confirm' => "Δεν θα μπορέσετε να επαναφέρετε αυτό το στοιχείο!",
    'delete_title_confirm' => "Είστε σίγουρος/η",

    'action_show_data' => 'Προβολή',
    'action_add_data' => 'Προσθήκη',
    'action_delete_selected' => 'Διαγραφή',

    'action_label' => 'Ενέργεια',
    'action_detail_data' => 'Λεπτομέρειες',
    'action_edit_data' => 'Επεξεργασία',
    'action_delete_data' => 'Διαγραφή',

    'button_cancel' => 'Άκυρο',
    'button_add' => 'Προσθήκη',
    'button_edit' => 'Επεξεργασία',
    'button_back' => 'Πίσω',
    'button_save' => 'Αποθήκευση',
    'button_save_more' => 'Αποθήκευση & Νέο',
    'button_import' => 'Εισαγωγή δεδομένων',
    'button_export' => 'Εξαγωγή δεδομένων',
    'button_filter' => 'Ταξινόμηση & Φιλτράρισμα',
    'button_close' => 'Κλείσιμο',
    'button_submit' => 'Υποβολή',
    'button_logout' => 'Έξοδος',
    'button_sign_in' => 'Είσοδος',
    'button_selected_action' => 'Μαζικές ενέργειες',
    'button_download_file' => 'Κατέβασμα',
    'button_reset' => 'Επαναφορά',
    'button_add_to_table' => 'Προσθήκη στον πίνακα',

    'export_dialog_title' => "Εξαγωγή δεδομένων",
    'export_dialog_filename' => 'Όνομα αρχείου',
    'export_dialog_help_filename' => 'Μπορείτε να ονομάσετε το αρχείο όπως επιθυμείτε',
    'export_dialog_maxdata' => "Μέγιστα δεδομένα",
    'export_dialog_help_maxdata' => 'Ελάχιστο 1 και μέγιστο 100,000 γραμμές ανά εξαγωγή',
    'export_dialog_columns' => 'Πεδία',
    'export_dialog_format_export' => 'Μορφή εξόδου',
    'export_dialog_show_advanced' => 'Για προχωρημένους',
    'export_dialog_page_size' => 'Μέγεθος σελίδας',
    'export_dialog_set_default' => 'Ορισμός ως προεπιλεγμένου μεγέθους σελίδας',
    'export_dialog_page_orientation' => 'Προσανατολισμός σελίδας',

    'import_page_title' => 'Εισαγωγή δεδομένων :module',
    'dashboard_default_text' => 'Καλώς ορίσατε στο :appname',
    'form_back_to_list' => 'Πίσω στην λίστα :module',
    'not_logged_in' => 'Δεν είστε συνδεδεμένος/η!',
    'menu_navigation' => "Μενού",
    'table_data_not_found' => "Δεν υπάρχουν στοιχεία",
    "notice_delete_file_upload" => "* Εαν θέλετε να ανεβάσετε άλλο αρχείο, παρακαλώ πρώτα διαγράψτε το υπάρχων.",
    "file_broken" => "Το αρχείο φαίνεται κατεστραμμένο! Διαγράψτε το και ξαναδοκιμάστε.",

    'denied_access' => 'Δεν έχετε δικαιώματα προβολής αυτών των στοιχείων!',
    'denied_update' => 'Δεν έχετε δικαιώματα επεξεργασίας αυτών των στοιχείων!',
    'denied_create' => 'Δεν έχετε δικαιώματα προσθήκης τέτοιων των στοιχείων!',
    'denied_delete' => 'Δεν έχετε δικαιώματα διαγραφής αυτών των στοιχείων!',

    'user_image' => 'Εικόνα χρήστη',
    'online' => 'Συνδεδεμένος',
    'controller_route_404' => 'Δεν βρέθηκε Controller / Route',
    'home' => 'Αρχική',
    'Notifications' => 'Ειδοποιήσεις',
    'Privileges' => 'Δικαιώματα',
    'Privileges_Roles' => 'Ρόλοι',
    'Add_New_Privilege' => 'Προσθήκη δικαιώματος',
    'List_Privilege' => 'Λίστα δικαιωμάτων',
    'add_user' => 'Προσθήκη χρήστη',
    'List_users' => 'Λίστα χρηστών',
    'Menu_Management' => 'Διαχείριση μενού',
    'Add_New_Setting' => 'Προσθήκη ρύθμισης',
    'Add_New_Module' => 'Προσθήκη Module',
    'List_Module' => 'Λίστα Module',
    'Add_New_Statistic' => 'Προσθήκη στατιστικού',
    'List_Statistic' => 'Λίστα στατιστικών',
    'Add_New_API' => 'Προσθήκη API',
    'API_Generator' => 'API Generator',
    'Statistic_Builder' => 'Statistic Builder',
    'Module_Generator' => 'Module Generator',
    'settings' => 'Ρυθμίσεις',
    'Users_Management' => 'Διαχείριση χρηστών',
    'list_API' => 'List API (Documentation)',
    'Generate_Screet_Key' => 'Generate Secret Key',
    'Add_New_Email' => 'Προσθήκη Email',
    'List_Email_Template' => 'List Email Template',
    'Email_Templates' => 'Email Templates',
    'Log_User_Access' => 'Log User Access',
    'SUPERADMIN' => 'SUPERADMIN',

    'click_here' => 'Κλικ εδώ',

    /*
     * this is for html direction to use in html and css classes like :
     * pull-left , pull-right , text-right ...
     * to make it easy to use the the view for rtl langs .
     * unless your language use right-to-left direction , you should keep it as it is :
     */
    'right' => 'right',
    'left' => 'left',

    'all_rights_reserved' => 'Πνευματικά δικαιώματα κατοχυρωμένα',
    'copyright' => '',
    'powered_by' => 'Εφαρμογή',

    'notification_you_have' => 'Έχετε',
    'notification_notification' => 'Ειδοποιήσεις',
    'notification_new' => 'Έχετε 1 ειδοποίηση!',

    'login_register_style' => 'Login Register Style',
    'email_setting' => 'Email Setting',
    'application_setting' => 'Application Setting',

    // table filter & sort 
    'filter_select_operator_type' => 'Select Operator Type',
    'filter_ascending' => 'ΑΥΞΟΥΣΑ',
    'filter_descending' => 'ΦΘΙΝΟΥΣΑ',
    'filter_equal_to' => '=(ίσο)',
    'filter_like' => 'LIKE',
    'filter_not_like' => 'NOT LIKE',
    'filter_greater_than_or_equal' => '>= (μεγαλύτερο ίσο)',
    'filter_less_than_or_equal' => '<= (μικρότερο ίσο)',
    'filter_less_than' => '< (λιγότερο από)',
    'filter_greater_than' => '> (μεγαλύτερο από)',
    'filter_not_equal_to' => '!= (άνισο με)',
    'filter_in' => 'IN',
    'filter_not_in' => 'NOT IN',
    'filter_between' => 'BETWEEN',
    'filter_sort_ascending' => 'Ταξινόμηση αύξουσα',
    'filter_sort_descending' => 'Ταξινόμηση φθίνουσα',
    'filter_eg' => 'π.χ.',
    'filter_lorem_ipsum' => 'Lorem ipsum',
    'filter_lorem_ipsum_dolor_sit' => ' Lorem,Ipsum,Dolor Sit',
    'filter_search' => 'Αναζήτηση',
    'filter_from' => 'από',
    'filter_to' => 'έως',
    'filter_sorting' => 'Ταξινόμηση',

    // confirmation
    'confirmation_yes' => 'Ναι!',
    'confirmation_no' => 'Όχι',

    //filemanager
    'chose_an_image' => 'Επιλέξτε εικόνα ',
    'chose_an_file' => 'Επιλέξτε αρχείο ',

    //action confirmation
    'confirmation_title' => 'Επιβεβαίωση',
    'confirmation_text' => 'Είστε σίγουροι πως θέλετε να ολοκληρώσετε αυτή την ενέργεια;',
    'confirmButtonText' => 'Ναι',

    //datamodal 
    'datamodal_select' => 'Επιλογή',
    'datamodal_search_and_enter' => 'Αναζήτηση και enter...',
    'datamodal_enter_to_search' => 'Εισαγωγή προς αναζήτηση',
    'datamodal_browse_data' => 'Εξερεύνηση δεδομένων',
    'datamodal_browse_file' => 'Εξερεύνηση αρχείων',

    //child 
    'table_detail' => 'Λεπτομέρειες πίνακα',
    'your_file_size_is_too_big' => 'Το μέγεθος του αρχείου είναι πολύ μεγάλο',
    'save_changes' => 'Αποθήκευση αλλαγών',
    'please_complete_the_form' => 'Παρακαλώ συμπληρώστε την φόρμα!',
    'this_field_is_required' => 'Αυτό το πεδίο απαιτείται',
    'text_form' => 'Φόρμα',
    "your_file_extension_is_not_allowed " => "Αυτό το είδος αρχείου δεν επιτρέπεται!",

    'toggle_navigation' => "Toggle navigation",
    'information' => "Information",

];
