<?php
return [
    'email_footer' => 'Non rispondere a questo indirizzo email. La mail è stata inviata dal sistema. ',
    'login_message' => 'Esegui il login per avviare la sessione',
    'text_forgot_password' => 'Password dimenticata ?',
    'page_title_login' => 'Pagina di Login',
    'page_title_forgot' => 'Password dimenticata',
    'forgot_message' => 'Inserisci il tuo indirizzo email per richiedere la password',
    "forgot_text_try_again" => "Riprovare il login?",
    'text_no_notification' => "Hai 0 notifiche",
    'text_view_all_notification' => 'Vedi tutto',
    'label_button_profile' => "Profilo",
    'filter_dialog_title' => 'Ordinamento e filtri avanzati',
    'there_is_no_option' => 'Non ci sono options setting per questo inputType',
    'no' => 'No.',

    'text_enter_the_password' => 'Inserisci la tua password per recuperare la sessione',
    'text_or_sign_in' => 'Oppure fai il login con un altro utente',
    'text_default_add_new_module' => 'Aggiungi nuovo :module',
    'text_default_list_module' => 'Lista :module',
    'text_default_help_password' => 'Minimo 5 caratteri. Lasciare vuoto per non cambiare la password.',
    'text_default_help_upload' => 'Tipo di file supportati : JPG, JPEG, PNG, GIF, BMP',
    'text_default_help_number' => 'Puoi inserire solo numeri',
    'text_default_help_email' => 'Inserire un indirizzo email valido',
    'text_default_help_text' => 'Puoi inserire solo caratter',
    'text_default_help_url' => 'Inserire un URL valido',
    'text_dashboard' => 'Dashboard',
    'text_delete' => 'Elimina',
    'text_prefix_option' => '** Seleziona un ',
    'text_loading' => 'Attendere caricamento in corso...',

    'message_after_logout' => 'Grazie, ci vediamo dopo!',
    'message_forgot_password' => 'Ti abbiamo inviato una nuova password nella tua casella email controlla la posta in arrivo o la posta in spam!',

    'page_not_found' => 'Oops! Pagina non trovata',
    'page_not_found_text' => 'Non troviamo la pagina che stai cercando.',
    'page_not_found_tips' => '* Assicurati che l\'URL sia corretto<br/>
                * Controlla che le maiuscole e minuscole siano corrette<br/>
                * Forse la pagina che stai cercando è stata eliminata dall\'admin<br/>
                * Puoi tornare indietro utilizzando il tasto back del browser<br/>',

    'alert_delete_selected' => 'Sicuro di voler eliminare i dati selezionati?',
    'alert_delete_selected_success' => 'Eliminazione effettuata con successo !',
    'alert_bulk_action_button' => 'Sei sicuro di voler ',
    'alert_action' => 'Hai :action correttamente !',
    'alert_add_data_success' => 'I dati sono stati inseriti !',
    'alert_add_data_failed' => 'Errore nel salvataggio dei dati !',
    'alert_update_data_success' => 'Aggiornamento eseguito !',
    'alert_update_data_failed' => 'Errore nell\'aggiornamento dei dati',
    'alert_delete_data_success' => 'Eliminazione eseguita con successo !',
    'alert_want_to_logout' => 'Vuoi effettuare il logout ?',
    'alert_warning' => "Oops",
    'alert_danger' => 'Qualcosa è andato storto ....',
    'alert_success' => 'Wow, ben fatto...',
    'alert_info' => 'Informazioni',
    'alert_primary' => 'Informazioni',
    'alert_session_expired' => 'La sessione è scaduta, effettua nuovamente il login  !',
    'alert_password_wrong' => 'Password errata !',
    'alert_required' => 'Verifica che tutti i campi richiesti siano stati inseriti correttamente',
    'alert_error_ajax' => 'Okay, E\' imbarazzante, ma qualcosa è andato storto, lo sistemeremo al più presto!',
    'alert_validation_error' => 'Compila correttamente il form : :error',
    'alert_select_a_data' => 'Seleziona almeno un dato!',

    'add_data_page_title' => 'Aggiungi :module',
    'edit_data_page_title' => 'Modifica :module',
    'detail_data_page_title' => 'Vedi :module',

    'default_module_description' => 'Elenco dati',

    'delete_description_confirm' => "Non sarai in grado di ripristinare i dati!",
    'delete_title_confirm' => "Sei sicuro ?",

    'action_show_data' => 'Vedi i dati',
    'action_add_data' => 'Aggiungi un nuovo dato',
    'action_delete_selected' => 'Elimina selezionati',

    'action_label' => 'Azione',
    'action_detail_data' => 'Vedi',
    'action_edit_data' => 'Modifica',
    'action_delete_data' => 'Elimina',

    'button_cancel' => 'Cancella',
    'button_add' => 'Aggiungi',
    'button_edit' => 'Modifica',
    'button_back' => 'Indietro',
    'button_save' => 'Salva',
    'button_save_more' => 'Salva & Aggiungi un altro',
    'button_import' => 'Importa Dati',
    'button_export' => 'Esporta Dati',
    'button_filter' => 'Ordina & Filtra',
    'button_close' => 'Chiudi',
    'button_submit' => 'Invia',
    'button_logout' => 'Logout',
    'button_sign_in' => 'Accedi',
    'button_selected_action' => 'Azioni di massa',
    'button_download_file' => 'Download file',
    'button_reset' => 'Reset',
    'button_add_to_table' => 'Aggiungi alla tabella',

    'export_dialog_title' => "Esporta Dati",
    'export_dialog_filename' => 'Nome file',
    'export_dialog_help_filename' => 'Puoi rinominare il file a tuo piacimento',
    'export_dialog_maxdata' => "Max Data",
    'export_dialog_help_maxdata' => 'Minimo 1 e massimo 100,000 righe per sessione di esportazione',
    'export_dialog_columns' => 'Colonne',
    'export_dialog_format_export' => 'Formato esportazione',
    'export_dialog_show_advanced' => 'Visualizza esportazione avanzata',
    'export_dialog_page_size' => 'Formato Pagina',
    'export_dialog_set_default' => 'Imposta come Formato Pagina di default',
    'export_dialog_page_orientation' => 'Orientamento Pagina',

    'import_page_title' => 'Importa dati :module',
    'dashboard_default_text' => 'Benvenuto nella dashboard di :appname',
    'form_back_to_list' => 'Torna all\'elenco :module',
    'not_logged_in' => 'Non sei loggato!',
    'menu_navigation' => "Menù di navigazione",
    'table_data_not_found' => "Nessun dato",
    "notice_delete_file_upload" => "* Se vuoi caricare un altro file, elimina prima il corrente.",
    "file_broken" => "Sembra che il file sia corrotto !. Clicca Elimina e procedi al ri-upload.",

    'denied_access' => 'Non hai il permesso di accedere a quest\'area !',
    'denied_update' => 'Non hai il privilegio per aggiornare i dati !',
    'denied_create' => 'Non hai il privilegio per inserire un nuovo dato!',
    'denied_delete' => 'Non hai il privilegio per eliminare il dato !',

    'user_image' => 'Immagine utente',
    'online' => 'Online',
    'controller_route_404' => 'Controller / Route Not Found',
    'home' => 'Home',
    'Notifications' => 'Notifiche',
    'Privileges' => 'Ruoli',
    'Privileges_Roles' => 'Ruoli',
    'Add_New_Privilege' => 'Aggiungi un nuovo ruolo',
    'List_Privilege' => 'Elenco ruoli',
    'add_user' => 'Aggiungi utente',
    'List_users' => 'Elenco utenti',
    'Menu_Management' => 'Gestione Menu',
    'Add_New_Setting' => 'Aggiungi un nuovo setting',
    'Add_New_Module' => 'Aggiungi un nuovo modulo',
    'List_Module' => 'Elenco moduli',
    'Add_New_Statistic' => 'Aggiungi una nuova statistica',
    'List_Statistic' => 'Elenco statistiche',
    'Add_New_API' => 'Aggiungi nuova API',
    'API_Generator' => 'Generatore di API',
    'Statistic_Builder' => 'Statistic Builder',
    'Module_Generator' => 'Generatore Moduli',
    'settings' => 'Impostazioni',
    'Users_Management' => 'Gestione utenti',
    'list_API' => 'Elenco API (Documentazione)',
    'Generate_Screet_Key' => 'Crea Secret Key',
    'Add_New_Email' => 'Aggiungi nuova Email',
    'List_Email_Template' => 'Elenco Template Email',
    'Email_Templates' => 'Template Email',
    'Log_User_Access' => 'Log Accessi utenti',
    'SUPERADMIN' => 'SUPERADMIN',

    'click_here' => 'Click qui',

    /*
     * this is for html direction to use in html and css classes like :
     * pull-left , pull-right , text-right ...
     * to make it easy to use the the view for rtl langs .
     * unless your language use right-to-left direction , you should keep it as it is :
     */
    'right' => 'right',
    'left' => 'left',

    'all_rights_reserved' => 'Tutti i diritti riservati',
    'copyright' => 'Copyright',
    'powered_by' => 'Powered by',

    'notification_you_have' => 'Hai',
    'notification_notification' => 'Notifiche',
    'notification_new' => 'Hai una nuova notifica!',

    'login_register_style' => 'Login Register Style',
    'email_setting' => 'Impostazioni Email',
    'application_setting' => 'Impostazioni Applicatione',

    // table filter & sort 
    'filter_select_operator_type' => 'Select Operator Type',
    'filter_ascending' => 'ASCENDING',
    'filter_descending' => 'DESCENDING',
    'filter_equal_to' => '=(Equal to)',
    'filter_like' => 'LIKE',
    'filter_not_like' => 'NOT LIKE',
    'filter_greater_than_or_equal' => '>= (Greater Than or Equal)',
    'filter_less_than_or_equal' => '<= (Less Than or Equal)',
    'filter_less_than' => '< (Less Than)',
    'filter_greater_than' => '> (Greater Than)',
    'filter_not_equal_to' => '!= (Not Equal to)',
    'filter_in' => 'IN',
    'filter_not_in' => 'NOT IN',
    'filter_between' => 'BETWEEN',
    'filter_sort_ascending' => 'Sort ascending',
    'filter_sort_descending' => 'Sort Descending',
    'filter_eg' => 'e.g',
    'filter_lorem_ipsum' => 'Lorem ipsum',
    'filter_lorem_ipsum_dolor_sit' => ' Lorem,Ipsum,Dolor Sit',
    'filter_search' => 'Search',
    'filter_from' => 'from',
    'filter_to' => 'to',
    'filter_sorting' => 'Sorting',

    // confirmation
    'confirmation_yes' => 'Si!',
    'confirmation_no' => 'No',

    //filemanager
    'chose_an_image' => 'Scegli un immagine ',
    'chose_an_file' => 'Scegli un file ',

    //action confirmation
    'confirmation_title' => 'Conferma',
    'confirmation_text' => 'Sicuro di voler eseguire questa azione?',
    'confirmButtonText' => 'Si',

    //datamodal
    'datamodal_select' => 'Select',
    'datamodal_search_and_enter' => 'Cerca e premi invio...',
    'datamodal_enter_to_search' => 'premi invio per cercare',
    'datamodal_browse_data' => 'Esplora dati',
    'datamodal_browse_file' => 'Esplora file',

    //child 
    'table_detail' => 'Dettaglio tabella',
    'your_file_size_is_too_big' => 'File troppo grande!',
    'save_changes' => 'Salva cambiamenti',
    'please_complete_the_form' => 'Completa il form !',
    'this_field_is_required' => 'Questo campo è obbligatorio',
    'text_form' => 'Form',
    "your_file_extension_is_not_allowed " => "Estensione file non permessa!",

    'toggle_navigation' => "Toggle navigation",
];
