<?php
return [
    'emaill_footer' => 'No respondas a este mensaje, es un mensaje generado automáticamente.',
    'login_message' => 'Por favor, inicia sesión para comenzar',
    'text_forgot_password' => '¿Olvidaste tu contraseña?',
    'page_title_login' => 'Inicio de sesión',
    'page_title_forgot' => 'Recuperar contraseña',
    'forgot_message' => 'Introduce tu dirección de correo electrónico para enviarte tu nueva contraseña',
    "forgot_text_try_again" => "¿Volver a iniciar sesión?",
    'text_no_notification' => "No tienes notificaciones",
    'text_view_all_notification' => 'Ver todas',
    'label_button_profile' => "Perfil",
    'filter_dialog_title' => 'Filtros y búsquedas avanzadas',
    'text_enter_the_password' => 'Introduce la contraseña para volver a la sesión',
    'text_or_sign_in' => 'O inicia sesión con otro usuario',
    'text_default_add_new_module' => 'Añadir nuevo :module',
    'text_default_list_module' => 'Ver :module',
    'text_default_help_password' => 'Mínimo 5 caracteres. Deja este campo vacio si no solicitaste un cambio de contraseña.',
    'text_default_help_upload' => 'Tipo de imágenes soportados: JPG, JPEG, PNG, GIF, BMP',
    'text_default_help_number' => 'Puedes introducir solo un número',
    'text_default_help_email' => 'Introduce una dirección de correo electrónico válida',
    'text_default_help_text' => 'Puedes introducir solo una letra',
    'text_default_help_url' => 'Introduce una dirección web (URL) válida',
    'text_dashboard' => 'Escritorio',
    'text_prefix_option' => '** Selecciona un',
    'text_loading' => 'Espera un segundo, por favor. Cargando...',
    'message_after_logout' => '¡Gracias por la visita, nos vemos pronto!',
    'message_forgot_password' => 'Te hemos enviado una nueva contraseña. Revisa tu correo electrónico. ¡Puede estar en la carpeta de spam!',
    'page_not_found' => 'Vaya, esta página no existe o no tienes acceso.',
    'page_not_found_text' => 'No encontramos la página que nos pides.',

    'page_not_found_tips' => '* Asegúrate que la dirección es la correcta<br/>
                * Recuerda que el sistema distingue entre mayúsculas y minúsculas<br/>
                * Consulta con el administrador, puede que haya eliminado esta página<br/>
                * Puedes regresar a la página anterior haciendo click en la flecha hacia atras del navegador<br/>',

    'log_try_view' => 'Intentar ver :name en :module',
    'log_try_edit' => 'Intentar editar :name en :module',
    'log_try_add' => 'Intentar añadir datos al :module',
    'log_try_add_save' => 'Intentar añadir :name data en :module',
    'log_try_delete' => 'Intentar eliminar :name en :module',
    'log_try_delete_selected' => 'Intentar eliminar el :module',
    'log_try_delete_image' => 'Intentar eliminar la imagen de :name en módulo :module',
    'log_try_update' => 'Intentar actualizar el :name en :module',
    'log_add' => 'Añadir nueva información :name en :module',
    'log_update' => 'Actualizar información :name en :module',
    'log_delete' => 'Eliminar información :name en :module',
    'log_delete_image' => 'Eliminar la imagen de :name en :module',
    'log_login' => 'Ingreso de :email desde la Dirección IP :ip',
    'log_forgot' => 'Alguien con la dirección IP :ip solicitó su contraseña por email a :email',
    'log_logout' => ':email se desconectó',
    'alert_delete_selected' => '¿Seguro que quieres eliminar todos los elementos seleccionados?',
    'alert_delete_selected_success' => '¡El borrado de los elementos seleccionados se ha completado con éxito!',
    'alert_bulk_action_button' => 'Está seguro que quiere',
    'alert_action' => '¡Has :action con éxito!',
    'alert_add_data_success' => '¡Los datos han sido añadidos!',
    'alert_add_data_failed' => '¡Algo ha fallado al grabar los datos!',
    'alert_update_data_success' => '¡Los datos han sido actualizados con éxito!',
    'alert_update_data_failed' => 'Algo ha fallado al actualizar los datos',
    'alert_delete_data_success' => '¡Borrado de datos con éxito!',
    'alert_want_to_logout' => '¿Quieres finalizar la sesión?',
    'alert_warning' => "¡Upss!",
    'alert_danger' => 'Parece que algo no funciona...',
    'alert_success' => 'Hecho, buen trabajo...',
    'alert_info' => 'Información',
    'alert_primary' => 'Información',
    'alert_session_expired' => 'Has superado el tiempo máximo de sesión, Inicia sesión de nuevo. Gracias !',
    'alert_password_wrong' => 'Lo sentimos, la contraseña esta mal escrita !',
    'alert_required' => 'Asegurate que has rellenado todos los campos obligatorios',
    'alert_error_ajax' => 'Parece que tenemos problemas en el sistema, vamos a intentar corregirlo lo antes posible !',
    'alert_validation_error' => 'Rellena el formulario correctamente : :error',
    'alert_select_a_data' => 'Por favor, seleccione al menos un registro',

    'add_data_page_title' => 'Añadir :module',
    'edit_data_page_title' => 'Editar :module',
    'button_add_to_table' => 'Agregar a la Tabla',

    'detail_data_page_title' => 'Detalles :module',

    'default_module_description' => 'Listado',

    'delete_description_confirm' => "No podrás recuperar estos datos!",
    'delete_title_confirm' => "Estás Seguro?",

    'action_show_data' => 'Mostrar',
    'action_add_data' => 'Añadir',
    'action_delete_selected' => 'Elimina los seleccionados',

    'action_label' => 'Acción',
    'action_detail_data' => 'Detalles',
    'action_edit_data' => 'Editar',
    'action_delete_data' => 'Eliminar',

    'button_cancel' => 'Cancelar',
    'button_add' => 'Añadir',
    'button_edit' => 'Editar',
    'button_back' => 'Volver',
    'button_save' => 'Guardar',
    'button_save_more' => 'Guardar y Añadir otro',
    'button_import' => 'Importar',
    'button_export' => 'Exportar',
    'button_filter' => 'Filtros y Orden',
    'button_close' => 'Cerrar',
    'button_submit' => 'Enviar',
    'button_logout' => 'Salir',
    'button_sign_in' => 'Iniciar',
    'button_selected_action' => 'Acciones Masivas',
    'button_download_file' => 'Descargar Fichero',
    'button_reset' => 'Resetear',
    'button_add_to_table' => 'Agregar a la Tabla',

    'export_dialog_title' => "Exportar Datos",
    'export_dialog_filename' => 'Nombre Fichero',
    'export_dialog_help_filename' => 'Puedes renombrar el fichero como desees',
    'export_dialog_maxdata' => "Max Data",
    'export_dialog_help_maxdata' => 'Mínimo 1 y máximo 100,000 registros por sesión',
    'export_dialog_columns' => 'Columnas',
    'export_dialog_format_export' => 'Formato Exportación',
    'export_dialog_show_advanced' => 'Muestra Exportaciones avanzadas',
    'export_dialog_page_size' => 'Tamaño de Página',
    'export_dialog_set_default' => 'Utilizar como tamaño por defecto',
    'export_dialog_page_orientation' => 'Orientación',

    'import_page_title' => 'Importar :module',
    'dashboard_default_text' => 'Bienvenido a  :appname',
    'form_back_to_list' => 'Volver al listado :module',
    'not_logged_in' => 'No has iniciado sesión !',
    'menu_navigation' => "Navegación",
    'table_data_not_found' => "No tenemos datos disponibles",
    "notice_delete_file_upload" => "* Si quieres subir otro fichero, antes elimina el fichero origen.",
    "file_broken" => "Parece que no se ha subido bien el fichero. Elimínalo y vuelve a intentarlo.",
    'denied_access' => '¡Vaya, no tienes permisos para acceder a este area!',
    'denied_update' => '¡Vaya, no tienes permisos para actualizar datos!',
    'denied_create' => '¡Vaya, no tienes permisos para añadir datos!',
    'denied_delete' => '¡Vaya, no tienes permisos para eliminar datos!',
    'user_image' => 'Imagen de usuario',
    'online' => 'En línea',
    'controller_route_404' => 'Controlador o Ruta no encontrado(a).',
    'home' => 'Principal',
    'Notifications' => 'Notificaciones',
    'Privileges' => 'Privilegios',
    'Privileges_Roles' => 'Privilegios & Roles',
    'Add_New_Privilege' => 'Añadir Nuevo Privilegio',
    'List_Privilege' => 'Ver Privilegios',
    'add_user' => 'Añadir Usuario',
    'List_users' => 'Ver Usuarios',
    'Menu_Management' => 'Gestión de Menús',
    'Add_New_Setting' => 'Añadir Nuevo Ajuste',
    'Add_New_Module' => 'Añadir Nuevo Módulo',
    'List_Module' => 'Ver Módulos',
    'Add_New_Statistic' => 'Añadir Nueva Estadística',
    'List_Statistic' => 'Ver Estadíticas ',
    'Add_New_API' => 'Crear Nueva API',
    'API_Generator' => 'Generador de API',
    'Statistic_Builder' => 'Generador de Estadísticas',
    'Module_Generator' => 'Generador de Módulos',
    'settings' => 'Ajustes',
    'Users_Management' => 'Gestión de usuarios',
    'list_API' => 'Ver API (Documentación)',
    'Generate_Screet_Key' => 'Generar Secret Key',
    'Add_New_Email' => 'Añadir Nuevo Email',
    'List_Email_Template' => 'Ver Plantillas de Correo',
    'Email_Templates' => 'Plantillas de Correo',
    'Log_User_Access' => 'Log de Accesos (Usuarios)',
    'SUPERADMIN' => 'SUPERADMIN',
    'click_here' => 'Haz click aquí',
    /*
     * this is for html direction to use in html and css classes like :
     * pull-left , pull-right , text-right ...
     * to make it easy to use the the view for rtl langs .
     * unless your language use right-to-left direction , you should keep it as it is :
     */
    'right' => 'right',
    'left' => 'left',
    'all_rights_reserved' => 'Todos los Derechos Reservados',
    'copyright' => 'Copyright',
    'powered_by' => 'Desarrollado por',
    'notification_you_have' => 'Tienes',
    'notification_notification' => 'Notificaciones',
    'notification_new' => '¡Tienes 1 nueva notificación!',
    'login_register_style' => 'Estilo de página de registro',
    'email_setting' => 'Ajustes de Correo',
    'application_setting' => 'Ajustes de Aplicaciones',
    // table filter & sort 
    'filter_select_operator_type' => 'Selecciona el tipo de operador',
    'filter_ascending' => 'Ascendentemente',
    'filter_descending' => 'Descendentemente',
    'filter_equal_to' => '= (Igual a)',
    'filter_like' => 'Contiene',
    'filter_not_like' => 'No contiene',
    'filter_greater_than_or_equal' => '>= (Mayor o Igual que)',
    'filter_less_than_or_equal' => '<= (Menor o Igual que)',
    'filter_less_than' => '< (Menor que)',
    'filter_greater_than' => '> (Mayor que)',
    'filter_not_equal_to' => '!= (Deferente de)',
    'filter_in' => 'Incluye',
    'filter_not_in' => 'No Incluye',
    'filter_between' => 'Entre',
    'filter_sort_ascending' => 'Ordenar Ascendentemente',
    'filter_sort_descending' => 'Ordenar Descendentemente',
    'filter_eg' => 'Ej.:',
    'filter_lorem_ipsum' => 'Lorem ipsum',
    'filter_lorem_ipsum_dolor_sit' => ' Lorem, Ipsum, Dolor Sit',
    'filter_search' => 'Buscar',
    'filter_from' => 'Desde',
    'filter_to' => 'Hasta',
    'filter_sorting' => 'Sorting',
    'filter_rows_total' => 'Total de registros',
    'filter_rows_to' => 'a',
    'filter_rows_of' => 'de',
    // confirmation
    'confirmation_yes' => '¡Sí!',
    'confirmation_no' => 'No',
    //filemanager
    'chose_an_image' => 'Elige una imagen ',
    'chose_an_file' => 'Elige un fichero ',

    // privilege
    'privileges_name' => 'Nombre del Privilegio',
    'privileges_super_admin' => 'Super Admin',
    'privileges_standart_user' => 'Usuario Estándar',
    'privileges_ID' => 'ID',
    'set_as_superadmin' => 'Establecer como Superadmin',
    'chose_theme_color_select' => '** Escoger color del tema',
    'chose_theme_color' => ' Color del Tema',
    'privileges_configuration' => 'Configuración de Privilegios',
    'privileges_module_list_no' => 'No.',
    'privileges_module_list_mod_names' => 'Módulos',
    'privileges_module_list_view' => 'Ver',
    'privileges_module_list_create' => 'Crear',
    'privileges_module_list_read' => 'Leer',
    'privileges_module_list_update' => 'Actualizar',
    'privileges_module_list_delete' => 'Eliminar',

    //datamodal

    'datamodal_select' => 'Seleccionar',
    'datamodal_search_and_enter' => 'Buscar y enter...',
    'datamodal_enter_to_search' => 'Enter para buscar',
    'datamodal_browse_data' => 'Escoger Dato',

    //action confirmation
    'confirmation_title' => 'Confirmación',
    'confirmation_text' => '¿Está seguro que desea realizar esta acción?',

    'datamodal_browse_file' => 'Escoger Archivo',

    //child 
    'table_detail' => 'Tabla de Detalles',
    'your_file_size_is_too_big' => 'El tamaño del archivo es demasiado grande',
    'save_changes' => 'Guardar Cambios',
    'please_complete_the_form' => 'Por favor, complete el formulario!',
    'this_field_is_required' => 'Este campo es requerido',
    'text_form' => 'Formulario',
    "your_file_extension_is_not_allowed " => "La extensión del archivo no es permitida!",
];
