<?php
return [
    'email_footer' => 'Não responda a esse e-mail. Esta é uma mensagem gerada automaticamente. ',
    'login_message' => 'Faça o login para iniciar a sessão',
    'text_forgot_password' => 'Esqueceu a senha?',
    'page_title_login' => 'Painel de Login',
    'page_title_forgot' => 'Esqueceu a senha',
    'forgot_message' => 'Digite seu e-mail para requisitar a senha',
    "forgot_text_try_again" => "Tentar login novamente ?",
    'text_no_notification' => "Você tem 0 notificação",
    'text_view_all_notification' => 'Visualizar tudo',
    'label_button_profile' => "Perfil",
    'filter_dialog_title' => 'Filtro e ordernação avançados',
    'text_enter_the_password' => 'Digite sua senha para recuperar sua sessão',
    'text_or_sign_in' => 'Ou entre como um usuário diferente',
    'text_default_add_new_module' => 'Adicionar novo :module',
    'text_default_list_module' => 'Listar :module',
    'text_default_help_password' => 'Mínimo de 5 caracteres. Por favor deixe vazio se você não quer alterar a senha.',
    'text_default_help_upload' => 'Tipos de arquivo suportado: JPG, JPEG, PNG, GIF, BMP',
    'text_default_help_number' => 'Você pode digitar somente números',
    'text_default_help_email' => 'Por favor digite um endereço de e-mail válido',
    'text_default_help_text' => 'Você pode digitar somente letras',
    'text_default_help_url' => 'Por favor insira um URL válido',
    'text_dashboard' => 'Painel de Controle',
    'text_prefix_option' => '** Por favor selecione',
    'text_loading' => 'Carregando... Por favor aguarde',
    'message_after_logout' => 'Obrigado, vejo você mais tarde!',
    'message_forgot_password' => 'Enviamos nova senha para seu e-mail, verifique a caixa de entrada ou de spam!',
    'page_not_found' => 'Oops! Página não encontrada',
    'page_not_found_text' => 'Não foi possível pesquisar na página que você está procurando.',
    'page_not_found_tips' => '* Verifique se o URL está correto<br/> 
                * Certifique-se de que a capitalização correta, pois é sensível a maiúsculas e minúsculas<br/> 
                * Talvez a página que você está procurando tenha sido excluída pelo Administrador<br/> 
                * Você pode voltar clicando no botão Voltar no navegador<br/>',
    'log_try_view' => 'Tente visualizar o conteúdo de :name em :module',
    'log_try_edit' => 'Tente editar o conteúdo de :name em :module',
    'log_try_add' => 'Tente adicionar conteúdo em :module',
    'log_try_add_save' => 'Tente adicionar o conteúdo de :name data em :module',
    'log_try_delete' => 'Tente excluir o conteúdo :name em :module',
    'log_try_delete_selected' => 'Tente excluir o selecionado em :module',
    'log_try_delete_image' => 'Tente excluir a imagem de :name em :module',
    'log_try_update' => 'Tente atualizar o conteúdo de :name em :module',
    'log_add' => 'Adicionar novo conteúdo de :name em :module',
    'log_update' => 'Atualizar dados de :name em :module',
    'log_delete' => 'Excluir o conteúdo de :name em :module',
    'log_delete_image' => 'Excluir a imagem de :name em :module',
    'log_login' => ':email se logou com o endereo de IP :ip',
    'log_forgot' => 'Algueḿ com o IP :ip solicitou uma senha para :email',
    'log_logout' => ':email sair',
    'alert_delete_selected' => 'Tem certeza de que deseja excluir todos os dados selecionados?',
    'alert_delete_selected_success' => 'Excluido com sucesso!',
    'alert_action' => ':action executado com sucesso!',
    'alert_add_data_success' => 'O conteúdo foi adicionado!',
    'alert_add_data_failed' => 'Falha ao salvar os dados!',
    'alert_update_data_success' => 'Os dados foram atualizados!',
    'alert_update_data_failed' => 'Falha ao atualizar os dados',
    'alert_delete_data_success' => 'Dados excluidos com sucesso!',
    'alert_want_to_logout' => 'Deseja sair?',
    'alert_warning' => "Oops",
    'alert_danger' => 'Algo deu errado...',
    'alert_success' => 'Uau, bom trabalho...',
    'alert_info' => 'Informação',
    'alert_primary' => 'Informação',
    'alert_session_expired' => 'Sua sessão expirou, por favor faça o login novamente!',
    'alert_password_wrong' => 'Desculpe, sua senha errada!',
    'alert_required' => 'Por favor, certifique-se de preencher todos os campos obrigatórios corretamente.',
    'alert_error_ajax' => 'Ok, é embaraçoso, algo deu mal, vamos corrigi-lo em breve!',
    'alert_validation_error' => 'Por favor preencha o formulário corretamente: :error',
    'add_data_page_title' => 'Adicionar :module',
    'edit_data_page_title' => 'Editar :module',
    'detail_data_page_title' => 'Detalhar :module',
    'default_module_description' => 'Lista de dados',
    'delete_description_confirm' => "Você não será capaz de recuperar esses dados de registro! You will not be able to recover this record data!",
    'delete_title_confirm' => "Você tem certeza?",
    'action_show_data' => 'Mostrar dados',
    'action_add_data' => 'Adicionar dados',
    'action_delete_selected' => 'Excluir selecionado',
    'action_label' => 'Ação',
    'action_detail_data' => 'Detalhar dados',
    'action_edit_data' => 'Editar dados',
    'action_delete_data' => 'Excluir',
    'button_cancel' => 'Cancelar',
    'button_add' => 'Adicionar dados',
    'button_edit' => 'Alterar dados',
    'button_back' => 'Voltar',
    'button_save' => 'Salvar',
    'button_save_more' => 'Salvar & Adicionar mais',
    'button_import' => 'Importar dados',
    'button_export' => 'Exportar dados',
    'button_filter' => 'Ordernar & Filtrar',
    'button_close' => 'Fechar',
    'button_submit' => 'Enviar',
    'button_logout' => 'Sair',
    'button_sign_in' => 'Cadastrar',
    'button_selected_action' => 'Ações em massa',
    'button_download_file' => 'Download',
    'button_reset' => 'Reset',
    'button_add_to_table' => 'Add To Table',

    'export_dialog_title' => "Exportar dados",
    'export_dialog_filename' => 'Nome do arquivo',
    'export_dialog_help_filename' => 'VocẼ pode renomear o arquivo de acordo com sua vontade',
    'export_dialog_maxdata' => "Dados máximos",
    'export_dialog_help_maxdata' => 'Mínimo entre 1 e o máximo de 100,000 linhas por exportação',
    'export_dialog_columns' => 'Colunas',
    'export_dialog_format_export' => 'Formato de exportação',
    'export_dialog_show_advanced' => 'Mostrar exportação avançada',
    'export_dialog_page_size' => 'Tamanho da página',
    'export_dialog_set_default' => 'Definir como tamanho de papel predifinido',
    'export_dialog_page_orientation' => 'Orientação da página',
    'import_page_title' => 'Importar dados de :module',
    'dashboard_default_text' => 'Bem-vindo ao Painel de Controle de :appname',
    'form_back_to_list' => 'Voltar para a lista de dados de :module',
    'not_logged_in' => 'Você não está logado!',
    'menu_navigation' => "Navegação",
    'table_data_not_found' => "Não há dados disponiveis",
    "notice_delete_file_upload" => "* Se você quiser carregar outro arquivo, primeiro excluia o arquivo.",
    "file_broken" => "Oops, parece que o arquivo estava quebrado. Clique em excluir e tente novamente.",
    'denied_access' => 'Desculpe, você não tem privilégios para acessar esta área!',
    'denied_update' => 'Desculpe, você não tem privilégio para atualizar os dados!',
    'denied_create' => 'Desculpe, você não tem privilégio para criar os dados!',
    'denied_delete' => 'Desculpe, você não tem privilégio para excluir os dados!',

    'user_image' => 'Imagem do usuário',
    'online' => 'Online',
    'controller_route_404' => 'Controle / Rota não encontra]',
    'home' => 'Inicio',
    'Notifications' => 'Notifications',
    'Privileges' => 'Privileges',
    'Privileges_Roles' => 'Privilégios',
    'Add_New_Privilege' => 'Adicionar novo Privilégio',
    'List_Privilege' => 'Listar Privilégios',
    'add_user' => 'Adicionar Usuário',
    'List_users' => 'Listar Uusário',
    'Menu_Management' => 'Gestão de menus',
    'Add_New_Setting' => 'Adicionar Nova Configuração',
    'Add_New_Module' => 'Adicionar Novo Modulo',
    'List_Module' => 'Listar Módulos',
    'Add_New_Statistic' => 'Adicionar nova estatistica',
    'List_Statistic' => 'Listas estatisticas',
    'Add_New_API' => 'Adicionar nova API',
    'API_Generator' => 'Gerador de API',
    'Statistic_Builder' => 'Construtor de Estatisticas',
    'Module_Generator' => 'Módulo Gerador',
    'settings' => 'Configurações',
    'Users_Management' => 'Gestão de usuários',
    'list_API' => 'Listar API (Documentação)',
    'Generate_Screet_Key' => 'Gerar nova chave secreta',
    'Add_New_Email' => 'Adicionar novo e-mail',
    'List_Email_Template' => 'Listar modelos de e-mail',
    'Email_Templates' => 'Modelos de e-mail',
    'Log_User_Access' => 'Histórico de acesso',
    'SUPERADMIN' => 'SUPER-ADMNISTRADOR',

    'click_here' => 'Clique aqui',

    /*
     * esse trecho serve para indicar sobre a orientação no html, assim como:
     * pull-left , pull-right , text-right ...
     * isso é para ficar mais facil de se usar com as linguagens rtl.
     * a menos que a leitura de sua linguagem seja da direita para esquerda, deixe dessa forma:
     */
    'right' => 'right',
    'left' => 'left',

    'all_rights_reserved' => 'Todos os Direitos Reservados',
    'copyright' => 'Copyright',
    'powered_by' => 'Desenvolvido por',

    'notification_you_have' => 'você tem',
    'notification_notification' => 'Notificações',
    'notification_new' => 'Você tem uma nova notificação!',

    'login_register_style' => 'Login Register Style',
    'email_setting' => 'Configurações de E-mail',
    'application_setting' => 'Configurações do Aplicativo',

    // table filter & sort
    'filter_select_operator_type' => 'Selecione o operador',
    'filter_ascending' => 'ASCENDENTE',
    'filter_descending' => 'DESCENDENTE',
    'filter_equal_to' => '=(Igual a)',
    'filter_like' => 'LIKE',
    'filter_not_like' => 'NOT LIKE',
    'filter_greater_than_or_equal' => '>>= (Maior que, ou igual)',
    'filter_less_than_or_equal' => '<= (Menor que, ou igual)',
    'filter_less_than' => '< (Menor que)',
    'filter_greater_than' => '> (Maior que)',
    'filter_not_equal_to' => '!= (Diferente de)',
    'filter_in' => 'IN',
    'filter_not_in' => 'NOT IN',
    'filter_between' => 'BETWEEN',
    'filter_sort_ascending' => 'Ordernação ascendente',
    'filter_sort_descending' => 'Ordernação descendente',
    'filter_eg' => 'ex.',
    'filter_lorem_ipsum' => 'Lorem ipsum',
    'filter_lorem_ipsum_dolor_sit' => ' Lorem,Ipsum,Dolor Sit',
    'filter_search' => 'Buscar',
    'filter_from' => 'de',
    'filter_to' => 'para',
    'filter_sorting' => 'Sorting',
    // confirmation
    'confirmation_yes' => 'Sim!',
    'confirmation_no' => 'Não',

    //filemanager
    'chose_an_image' => 'Escolha uma imagem ',
    'chose_an_file' => 'Escolha um arquivo ',

    //action confirmation
    'confirmation_title' => 'Confirmação',
    'confirmation_text' => 'Tem certeza de que quer fazer isso?',
    'confirmButtonText' => 'Sim',

    // privilege
    'privileges_name' => 'Nome do Privilégio',
    'privileges_super_admin' => 'Super Admin',
    'privileges_standart_user' => 'Usuário Padrão',
    'privileges_ID' => 'ID',

    'set_as_superadmin' => 'Configurar como Superadmin',
    'chose_theme_color_select' => '** Escolha a cor de fundo do tema',
    'chose_theme_color' => ' Cor do Tema',
    'privileges_configuration' => 'Configuração de Privilégios',
    'privileges_module_list_no' => 'Não.',
    'privileges_module_list_mod_names' => 'Nome dos Módulos',
    'privileges_module_list_view' => 'Visualizar',
    'privileges_module_list_create' => 'Criar',
    'privileges_module_list_read' => 'Ler',
    'privileges_module_list_update' => 'Atualizar',
    'privileges_module_list_delete' => 'Excluir',

    //datamodal
    'datamodal_select' => 'Select',
    'datamodal_search_and_enter' => 'Search and enter...',
    'datamodal_enter_to_search' => 'Enter to search',
    'datamodal_browse_data' => 'Browse Data',
    'datamodal_browse_file' => 'Browse File',

    //child 
    'table_detail' => 'Table Detail',
    'your_file_size_is_too_big' => 'Your file size is too big',
    'save_changes' => 'Save Changes',
    'please_complete_the_form' => 'Please complete the form !',
    'this_field_is_required' => 'This field is required',
    'text_form' => 'Form',
    "your_file_extension_is_not_allowed " => "Your file extension is not allowed !",
];
