<?php
return [
    'email_footer'               => 'هذه رسالة تلقائية ، الرجاء عدم الرد مباشرة على هذا البريد الإلكتروني .',
    'login_message'              => 'الرجاء تسجيل الدخول',
    'text_forgot_password'       => 'نسيت كلمة المرور ?',
    'page_title_login'           => 'تسجيل الدخول',
    'page_title_forgot'          => 'نسيت كلمة المرور',
    'forgot_message'             => 'ادخل بريدك الإلكتروني لاستعادة كلمة المرور',
    "forgot_text_try_again"      => " حاول تسجيل الدخول مرة اخرى ?",
    'text_no_notification'       => "لا توجد لديك تنبيهات",
    'text_view_all_notification' => 'عرض الكل',
    'label_button_profile'       => "الملف الشخصي",
    'filter_dialog_title'        => 'فرز متقدم',

    'text_enter_the_password'     => 'فضلا ادخل كلمة المرور لاستعادة جلسة العمل',
    'text_or_sign_in'             => 'او سجل الدخول بمستخدم مختلف',
    'text_default_add_new_module' => 'اضافة :module جديد',
    'text_default_list_module'    => 'عرض :module',
    'text_default_help_password'  => '٥ احرف فما فوق ، اترك الحقل فارغا اذا لا تريد تغيير كلمة المرور',
    'text_default_help_upload'    => 'الملفات المدعومة : JPG, JPEG, PNG, GIF, BMP',
    'text_default_help_number'    => 'ادخل ارقام فقط',
    'text_default_help_email'     => 'صيغة البريد الإلكتروني غير صحيحة',
    'text_default_help_text'      => 'فضلا ادخل احرف فقط',
    'text_default_help_url'       => 'فضلا ادخل رابط إلكتروني صحيح',
    'text_dashboard'              => 'الرئيسية',
    'text_prefix_option'          => '** فضلا اختر',
    'text_loading'                => 'فضلا الانتظار جاري التحميل ...',

    'message_after_logout'    => 'شكرا لك ، نراك لاحقا !',
    'message_forgot_password' => 'تم ارسال كلمة المرور إلى بريدك الإلكتروني !',

    'page_not_found'      => 'عفوا الصفحة غير موجودة',
    'page_not_found_text' => 'لم يتم العثور على الصفحة التي تبحث عنها.',
    'page_not_found_tips' => '* تآكد من ان الرابط صحيح<br/>
                * تآكد من الاحرف فهي حساسة للحالة<br/>
                * ربما تم حذف الصفحة<br/>
                * يمكنك العودة للخلف وتجربة رابط اخر<br/>',

    'log_try_view'            => 'حاول عرض  :name في :module',
    'log_try_edit'            => 'حاول تعديل بيانات :name في :module',
    'log_try_add'             => 'حاول اضافة بيانات في :module',
    'log_try_add_save'        => 'حاول اضافة بيانات :name data في :module',
    'log_try_delete'          => 'حاول حذف :name data في :module',
    'log_try_delete_selected' => 'حاول حذف في :module',
    'log_try_delete_image'    => 'حاول حذف الصور من :name data في :module',
    'log_try_update'          => 'حاول تعديل الاسم :name data في :module',
    'log_add'                 => 'اضافة بيانات جديدة :name في :module',
    'log_update'              => 'تعديل :name في :module',
    'log_delete'              => 'حذف :name في :module',
    'log_delete_image'        => 'حذف الصورة :name في :module',
    'log_login'               => ':email سجل دخل من رقم آيبي :ip',
    'log_forgot'              => 'شخصا ما من الآيبي :ip طلب اعاة تعيين كلمة المرور :email',
    'log_logout'              => ':email تسجيل خروج',

    'alert_delete_selected'         => 'هل آنت متآكد من حئف كافة البيانات المحددة ?',
    'alert_delete_selected_success' => 'البيانات المحددة تم حذفها بنجاح !',
    'alert_action'                  => 'تم :action بنجاح !',
    'alert_add_data_success'        => 'تم اضافة البيانات !',
    'alert_add_data_failed'         => 'فشل حفظ البيانات !',
    'alert_update_data_success'     => 'تم تحديث البيانات !',
    'alert_update_data_failed'      => 'فشل تحديث البيانات',
    'alert_delete_data_success'     => 'تم حذف البيانات !',
    'alert_want_to_logout'          => 'هل أنت متأكد من تسجيل الخروج ?',
    'alert_warning'                 => "عفوا ..",
    'alert_danger'                  => 'حدث خطأ ما  ....',
    'alert_success'                 => 'تم بنجاح ...',
    'alert_info'                    => 'معلومات',
    'alert_primary'                 => 'معلومات',
    'alert_session_expired'         => 'عفوا انتهت جلسة العمل ، فضلا اعد تسجيل الدخول !',
    'alert_password_wrong'          => 'عفو كلمة المرور خاطئة !',
    'alert_required'                => 'فضلا اكمل كافة الحقول المطلوبة',
    'alert_error_ajax'              => 'عفوا لقد حصل خطا ما ، سيتم حل المشكلة في اقرب وقت ممكن !',
    'alert_validation_error'        => 'فضلا اكمل الحقول بشكل صحيح : :error',

    'add_data_page_title'    => 'اضافة :module',
    'edit_data_page_title'   => 'تعديل :module',
    'detail_data_page_title' => 'تفاصيل :module',

    'default_module_description' => 'جدول البيانات',

    'delete_description_confirm' => "لا يمكنك التراجع عن عملية الحذف !",
    'delete_title_confirm'       => "هل آنت متأكد ؟",


    'action_show_data'       => 'عرض البيانات',
    'action_add_data'        => 'اضافة بيانات',
    'action_delete_selected' => 'حذف المحدد',

    'action_label'       => 'الاجراء',
    'action_detail_data' => 'التفاصيل',
    'action_edit_data'   => 'تعديل',
    'action_delete_data' => 'حذف',


    'button_cancel'          => 'إلغاء',
    'button_add'             => 'اضافة بيانات',
    'button_edit'            => 'تعديل بيانات',
    'button_back'            => 'للخلف',
    'button_save'            => 'حفظ',
    'button_save_more'       => 'حفظ واضافة المزيد',
    'button_import'          => 'استيراد البيانات',
    'button_export'          => 'تصدير البيانات',
    'button_filter'          => 'الفرز والتصفية',
    'button_close'           => 'اغلاق',
    'button_submit'          => 'حفظ',
    'button_logout'          => 'تسجيل الخروج',
    'button_sign_in'         => 'تسجيل الدخول',
    'button_selected_action' => 'الاجراء الجماعي',
    'button_download_file'   => 'تنزيل الملف',
    'button_reset'           => 'اعادة تعيين',

    'export_dialog_title'            => "تصدير البيانات",
    'export_dialog_filename'         => 'اسم الملف',
    'export_dialog_help_filename'    => 'يمكنك تغيير اسم الملف لما تراه مناسبا',
    'export_dialog_maxdata'          => "اكبر قيمة",
    'export_dialog_help_maxdata'     => 'اقصى حد لعمليات التصدير في الجسة : 100,000 عملية',
    'export_dialog_columns'          => 'اعمدة',
    'export_dialog_format_export'    => 'تنسيق التصدير',
    'export_dialog_show_advanced'    => 'خيارات التصدير المتقدمة',
    'export_dialog_page_size'        => 'مقاس الصفحة',
    'export_dialog_set_default'      => 'تعيين كحجم افتراضي لمقاسات الصفحات',
    'export_dialog_page_orientation' => 'اتجاه الصفحة',

    'import_page_title'         => 'استيراد :module',
    'dashboard_default_text'    => 'مرحبا بك في شاشة :appname',
    'form_back_to_list'         => 'العودة إلى قائمة البيانات :module',
    'not_logged_in'             => 'لم تقم بتسجيل الدخول !',
    'menu_navigation'           => "التنقل",
    'table_data_not_found'      => "لا توجد بيانات متوفرة",
    "notice_delete_file_upload" => "* يجب حذف الملف الموجود قبل تحميل ملف آخر.",
    "file_broken"               => "الملف معطوب ، فضلا احذف الملف واعد المحاولة .",

    'denied_access' => 'عفوا لاتملك الصلاحيات اللازمة للوصول لهذه الصفحة !',
    'denied_update' => 'عفوا لاتملك الصلاحيات اللازمة لتحديث البيانات !',
    'denied_create' => 'عفوا لاتملك الصلاحيات اللازمة لإنشاء بيانات جديدة !',
    'denied_delete' => 'عفوا لاتملك الصلاحيات اللازمة لحذف البيانات !',

    'user_image'           => 'الصورة الرمزية للمستخدم',
    'online'               => 'متصل',
    'controller_route_404' => 'لم يتم العثور على الرابط المطلوب',
    'home'                 => 'الرئيسية',

    'Privileges_Roles'    => 'صلاحيات الوصول',
    'Add_New_Privilege'   => 'اضافة صلاحية',
    'List_Privilege'      => 'عرض الصلاحيات',
    'add_user'            => 'اضافة مستخدم',
    'List_users'          => 'عرض المستخدمين',
    'Menu_Management'     => 'ادارة القوائم',
    'Add_New_Setting'     => 'اضافة اعدادات',
    'Add_New_Module'      => 'اضافة تطبيق',
    'List_Module'         => 'عرض التطبيقات',
    'Add_New_Statistic'   => 'اضافة احصائيات',
    'List_Statistic'      => 'عرض الاحصائيات',
    'Add_New_API'         => 'اضافة API',
    'API_Generator'       => 'انشاء API',
    'Statistic_Builder'   => 'الاحصائيات والرسوم البيانية',
    'Module_Generator'    => 'تطبيقات النظام',
    'settings'            => 'اعدادات النظام',
    'Users_Management'    => 'ادارة المستخدمين',
    'list_API'            => 'عرض API',
    'Generate_Screet_Key' => 'انشاء مفتاح',
    'Add_New_Email'       => 'اضافة قالب جديد',
    'List_Email_Template' => 'عرض القوالب',
    'Email_Templates'     => 'قوالب البريد الإلكتروني',
    'Log_User_Access'     => 'سجلات النظام',
    'SUPERADMIN'          => 'مدير النظام ',

    'click_here' => 'اضغط هنا ',

    /*
     * this is for html direction to use in html and css classes like :
     * pull-left , pull-right , text-right ...
     * to make it easy to use the the view for rtl langs .
     * unless your language use right-to-left direction , you should keep it as it is :
     */
    'right'      => 'left',
    'left'       => 'right',

    'all_rights_reserved' => 'كافة الحقوق محفوظة',
    'copyright'           => 'حقوق النسخ',
    'powered_by'          => 'انشئ بواسطة',

    'notification_you_have'     => 'لديك',
    'notification_notification' => 'تنبيهات',
    'notification_new'          => 'لديك تنبيه جديد',

    'login_register_style'         => 'شاشة الدخول والتسجيل',
    'email_setting'                => 'اعدادات البريد',
    'application_setting'          => 'اعدادات عامة',

    // table filter & sort
    'filter_select_operator_type'  => 'اختر نوع العملية',
    'filter_ascending'             => 'تصاعدي',
    'filter_descending'            => 'تنازلي',
    'filter_equal_to'              => '=(يساوي لـ)',
    'filter_like'                  => 'مثل',
    'filter_not_like'              => 'ليس مثل',
    'filter_greater_than_or_equal' => '>>= (اكبر من او يساوي)',
    'filter_less_than_or_equal'    => '<= (اصغر من او يساوي)',
    'filter_less_than'             => '< (اقل من)',
    'filter_greater_than'          => '> (اكبر من)',
    'filter_not_equal_to'          => '!= (لا يساوي لـ)',
    'filter_in'                    => 'ضمن',
    'filter_not_in'                => 'ليس ضمن',
    'filter_between'               => 'بين',
    'filter_sort_ascending'        => 'فرز تصاعدي',
    'filter_sort_descending'       => 'فرز تنازلي',
    'filter_eg'                    => 'مثال',
    'filter_lorem_ipsum'           => 'ابجدي',
    'filter_lorem_ipsum_dolor_sit' => ' Lorem,Ipsum,Dolor Sit',
    'filter_search'                => 'بحث',
    'filter_from'                  => 'من',
    'filter_to'                    => 'إلى',

    // confirmation
    'confirmation_yes'             => 'نعم!',
    'confirmation_no'              => 'لا',

    //filemanager
    'chose_an_image'               => 'اختر صورة ',
    'chose_an_file'                => 'اختر ملف ',
];
