<?php
return [
    'email_footer' => 'Jangan membalas email ke alamat email ini. Email ini dikirim secara otomatis oleh sistem kami.',
    'login_message' => 'Silahkan login untuk masuk',
    'text_forgot_password' => 'Lupa Password ?',
    'page_title_login' => 'Login Panel',
    'page_title_forgot' => 'Lupa Password ?',
    'forgot_message' => 'Masukkan email terdaftar anda untuk meminta password ulang.',
    "forgot_text_try_again" => "Cobalah login kembali ?",
    'text_no_notification' => "Anda mempunya 0 notifikasi",
    'text_view_all_notification' => 'Lihat Semua',
    'label_button_profile' => "Profil",
    'filter_dialog_title' => 'Pengurutan dan Filterisasi',
    'there_is_no_option' => 'Anda belum mengatur untuk tipe ini',

    'text_enter_the_password' => 'Masukkan password anda',
    'text_or_sign_in' => 'Atau login dengan akun lain',
    'text_default_add_new_module' => 'Tambah :module',
    'text_default_list_module' => 'Daftar :module',
    'text_default_help_password' => 'Minimal 5 karakter. Tinggalkan jika anda tidak mengubahnya',
    'text_default_help_upload' => 'Tipe file yang didukung: JPG, JPEG, PNG, GIF, BMP',
    'text_default_help_number' => 'Anda hanya dapat memasukkan angka saja',
    'text_default_help_email' => 'Mohon input alamat email dengan benar',
    'text_default_help_text' => 'Anda hanya dapat memasukkan huruf saja',
    'text_default_help_url' => 'Mohon masukkan URL yang benar',
    'text_dashboard' => 'Halaman Awal',
    'text_prefix_option' => '** Silahkan pilih',
    'text_loading' => 'Silahkan menunggu sebentar...',

    'message_after_logout' => 'Terima kasih, sampai jumpa lagi !',
    'message_forgot_password' => 'Kami telah mengirimkan password baru ke email anda, silahkan cek di inbox atau spambox!',

    'page_not_found' => 'Oops! Halaman tidak ditemukan',
    'page_not_found_text' => 'Kami tidak dapat menemukan halaman yang anda cari.',
    'page_not_found_tips' => '* Mohon pastikan URL yang anda kunjungi sudah benar<br/>
                * Mohon pastikan kesesuaian besar kecil karakter pada URL<br/>
                * Mungkin halaman yang anda kunjungi telah dihapus oleh Admin<br/>
                * Anda tetap bisa kembali ke halaman sebelumnya dengan menekan tombol back pada browser anda<br/>',

    'log_try_view' => 'Mencoba melihat data :name pada :module',
    'log_try_edit' => 'Mencoba mengubah data :name pada :module',
    'log_try_add' => 'Mencoba menambah data :module',
    'log_try_add_save' => 'Mencoba menambah data :name pada :module',
    'log_try_delete' => 'Mencoba menghapus :name data pada :module',
    'log_try_delete_selected' => 'Mencoba menghapus data terpilih :module',
    'log_try_delete_image' => 'Mencoba menghapus gambar :name data pada :module',
    'log_try_update' => 'Mencoba mengubah :name data pada :module',
    'log_add' => 'Tambah data baru :name pada :module',
    'log_update' => 'Memperbaharui data :name pada :module',
    'log_delete' => 'Menghapus data :name pada :module',
    'log_delete_image' => 'Menghapus gambar :name pada :module',
    'log_login' => ':email login dengan IP Address :ip',
    'log_forgot' => 'Seseorang dengan IP :ip meminta password ulang :email',
    'log_logout' => ':email keluar',

    'alert_delete_selected' => 'Apakah anda yakin ingin menghapus data yang terpilih ?',
    'alert_delete_selected_success' => 'Menghapus data terpilih berhasil !',
    'alert_bulk_action_button' => 'Apakah anda yakin untuk',
    'alert_action' => 'Anda telah :action dengan sukses !',
    'alert_add_data_success' => 'Data berhasil ditambahkan !',
    'alert_add_data_failed' => 'Gagal menambahkan data !',
    'alert_update_data_success' => 'Data berhasil diperbaharui !',
    'alert_update_data_failed' => 'Gagal memperbaharui data',
    'alert_delete_data_success' => 'Menghapus data berhasil !',
    'alert_want_to_logout' => 'Apakah anda ingin keluar ?',
    'alert_warning' => "Aduh",
    'alert_danger' => 'Sesuai yang tidak beres terjadi ....',
    'alert_success' => 'Berhasil !',
    'alert_info' => 'Informasi',
    'alert_primary' => 'Informasi',
    'alert_session_expired' => 'Sesi anda telah berakhir, harap masuk kembali !',
    'alert_password_wrong' => 'Maaf password anda salah !',
    'alert_required' => 'Mohon pastikan anda telah mengisi form dengan benar !',
    'alert_error_ajax' => 'Baiklah ini sangat memalukan, kami akan segera memperbaiki hal ini!',
    'alert_validation_error' => 'Mohon lengkapi form dengan benar: :error',

    'add_data_page_title' => 'Tambah :module',
    'edit_data_page_title' => 'Ubah :module',
    'detail_data_page_title' => 'Detil :module',

    'default_module_description' => 'Daftar',

    'delete_description_confirm' => "Anda tidak akan dapat mengembalikan data anda!",
    'delete_title_confirm' => "Apakah anda yakin ?",

    'action_show_data' => 'Tampilkan Data',
    'action_add_data' => 'Tambah Data',
    'action_delete_selected' => 'Hapus terpilih',

    'action_label' => 'Aksi',
    'action_detail_data' => 'Detil Data',
    'action_edit_data' => 'Ubah Data',
    'action_delete_data' => 'Hapus',

    'button_cancel' => 'Batal',
    'button_add' => 'Tambah Data',
    'button_edit' => 'Ubah Data',
    'button_back' => 'Kembali',
    'button_save' => 'Simpan',
    'button_save_more' => 'Simpan & Tambah Lagi',
    'button_import' => 'Impor Data',
    'button_export' => 'Ekspor Data',
    'button_filter' => 'Urutkan & Filter',
    'button_close' => 'Tutup',
    'button_submit' => 'Kirim Data',
    'button_logout' => 'Keluar',
    'button_sign_in' => 'Masuk',
    'button_selected_action' => 'Aksi Massal',
    'button_download_file' => 'Unduh file',
    'button_reset' => 'Ulangi',
    'button_add_to_table' => 'Add To Table',

    'export_dialog_title' => "Ekspor Data",
    'export_dialog_filename' => 'Nama File',
    'export_dialog_help_filename' => 'Anda dapat memberikan nama sesuai keinginan anda',
    'export_dialog_maxdata' => "Maksimal Data",
    'export_dialog_help_maxdata' => 'Minimal 1 dan maksimal 100,000 data per sesi',
    'export_dialog_columns' => 'Kolom',
    'export_dialog_format_export' => 'Format Ekspor',
    'export_dialog_show_advanced' => 'Tampilkan Ekspor Lanjutan',
    'export_dialog_page_size' => 'Ukuran Halaman',
    'export_dialog_set_default' => 'Atur sebagai ukuran standar',
    'export_dialog_page_orientation' => 'Orientasi Halaman',

    'import_page_title' => 'Impor Data :module',
    'dashboard_default_text' => 'Selamat datang di halaman awal :appname',
    'form_back_to_list' => 'Kembali ke halaman :module',
    'not_logged_in' => 'Anda belum login !',
    'menu_navigation' => "Navigasi",
    'table_data_not_found' => "Tidak ada data tersedia",
    "notice_delete_file_upload" => "* Jika anda ingin mengunggah file lain, silahkan hapus file ini terlebih dahulu",
    "file_broken" => "Aduh sepertinya file rusak, silahkan unggah ulang !",

    'denied_access' => 'Maaf anda tidak memiliki hak akses masuk ke area ini !',
    'denied_update' => 'Maaf anda tidak memiliki hak akses mengubah data!',
    'denied_create' => 'Maaf anda tidak memiliki hak akses menambah data !',
    'denied_delete' => 'Maaf anda tidak memiliki hak akses menghapus data!',

    'user_image' => 'Gambar Pengguna',
    'online' => 'Online',
    'controller_route_404' => 'Controller / Route tidak tersedia',
    'home' => 'Halaman Awal',
    'Notifications' => 'Notifications',
    'Privileges' => 'Privileges',
    'Privileges_Roles' => 'Detil Hak Akses',
    'Add_New_Privilege' => 'Tambah Hak Akses',
    'List_Privilege' => 'Daftar Hak Akses',
    'add_user' => 'Tambah Pengguna',
    'List_users' => 'Daftar Pengguna',
    'Menu_Management' => 'Pengolah Menu',
    'Add_New_Setting' => 'Tambah Pengaturan',
    'Add_New_Module' => 'Tambah Modul',
    'List_Module' => 'Daftar Modul',
    'Add_New_Statistic' => 'Tambah Statistik',
    'List_Statistic' => 'Daftar Statistik',
    'Add_New_API' => 'Tambah API',
    'API_Generator' => 'Pembangun Otomatis API',
    'Statistic_Builder' => 'Pembangun Statistik',
    'Module_Generator' => 'Pembangun Modul',
    'settings' => 'Pengaturan',
    'Users_Management' => 'Manajemen Pengguna',
    'list_API' => 'Daftar API (Dokumentasi)',
    'Generate_Screet_Key' => 'Buat Kunci Rahasia (API)',
    'Add_New_Email' => 'Tambah Kerangka Email',
    'List_Email_Template' => 'Daftar Kerangka Email',
    'Email_Templates' => 'Kerangka Email',
    'Log_User_Access' => 'Catatan Akses Pengguna',
    'SUPERADMIN' => 'Superadmin',

    'click_here' => 'Klik disini',

    /*
     * this is for html direction to use in html and css classes like :
     * pull-left , pull-right , text-right ...
     * to make it easy to use the the view for rtl langs .
     * unless your language use right-to-left direction , you should keep it as it is :
     */
    'right' => 'right',
    'left' => 'left',

    'all_rights_reserved' => 'All Rights Reserved',
    'copyright' => 'Copyright',
    'powered_by' => 'Powered by',

    'notification_you_have' => 'Anda memiliki',
    'notification_notification' => 'Notifikasi',
    'notification_new' => 'Anda mendapatkan notifikasi baru !',

    'login_register_style' => 'Login Register Style',
    'email_setting' => 'Pengaturan Email',
    'application_setting' => 'Pengaturan Aplikasi',

    // table filter & sort 
    'filter_select_operator_type' => 'Operator',
    'filter_ascending' => 'Kecil -> Besar',
    'filter_descending' => 'Besar <- Kecil',
    'filter_equal_to' => 'Sama dengan',
    'filter_like' => 'Seperti',
    'filter_not_like' => 'Tidak Seperti',
    'filter_greater_than_or_equal' => 'Lebih besar dan sama',
    'filter_less_than_or_equal' => 'Kurang dari dan sama',
    'filter_less_than' => 'Kurang dari',
    'filter_greater_than' => 'Lebih besar dari',
    'filter_not_equal_to' => 'Tidak sama',
    'filter_in' => 'Dalam pilihan',
    'filter_not_in' => 'Tidak dalam pilihan',
    'filter_between' => 'Diantara',
    'filter_sort_ascending' => 'Urutan Naik',
    'filter_sort_descending' => 'Urutan Turun',
    'filter_eg' => 'Cth',
    'filter_lorem_ipsum' => 'Lorem ipsum',
    'filter_lorem_ipsum_dolor_sit' => ' Lorem,Ipsum,Dolor Sit',
    'filter_search' => 'Cari',
    'filter_from' => 'Dari',
    'filter_to' => 'Ke',
    'filter_sorting' => 'Sorting',
    // confirmation
    'confirmation_yes' => 'Ya',
    'confirmation_no' => 'Tidak',

    //filemanager
    'chose_an_image' => 'Pilih gambar',
    'chose_an_file' => 'Pilih file ',

    //action confirmation
    'confirmation_title' => 'Konfirmasi',
    'confirmation_text' => 'Apakah anda yakin akan melakukan aksi ini?',
    'confirmButtonText' => 'Ya',

    // privilege
    'privileges_name' => 'Privilege Name',
    'privileges_super_admin' => 'Super Admin',
    'privileges_standart_user' => 'Standart user',
    'privileges_ID' => 'ID',
    'set_as_superadmin' => 'Set as Superadmin',
    'chose_theme_color_select' => '** Choose Backend Theme Color',
    'chose_theme_color' => ' Theme Color',
    'privileges_configuration' => 'Privileges Configuration',
    'privileges_module_list_no' => 'No.',
    'privileges_module_list_mod_names' => 'Module\'s Name',
    'privileges_module_list_view' => 'View',
    'privileges_module_list_create' => 'Create',
    'privileges_module_list_read' => 'Read',
    'privileges_module_list_update' => 'Update',
    'privileges_module_list_delete' => 'Delete',

    //datamodal 
    'datamodal_select' => 'Select',
    'datamodal_search_and_enter' => 'Search and enter...',
    'datamodal_enter_to_search' => 'Enter to search',
    'datamodal_browse_data' => 'Browse Data',
    'datamodal_browse_file' => 'Browse File',

    //child 
    'table_detail' => 'Table Detail',
    'your_file_size_is_too_big' => 'Your file size is too big',
    'save_changes' => 'Save Changes',
    'please_complete_the_form' => 'Please complete the form !',
    'this_field_is_required' => 'This field is required',
    'text_form' => 'Form',
    "your_file_extension_is_not_allowed " => "Your file extension is not allowed !",
];
