<?php
return [
    'email_footer'               => '此邮件为系统自动发送，请勿回复。',
    'login_message'              => '请用邮箱登录',
    'text_forgot_password'       => '忘记密码?',
    'page_title_login'           => '登录窗口',
    'page_title_forgot'          => '忘记密码',
    'forgot_message'             => '请输入您的电子邮件地址,以便找回您的密码',
    "forgot_text_try_again"      => "再次登录?",
    'text_no_notification'       => "你没有收到任何通知",
    'text_view_all_notification' => '查看全部',
    'label_button_profile'       => "个人中心",
    'filter_dialog_title'        => '筛选',
    'there_is_no_option'        => '该输入类型没有选择配置',
    'no'                          => 'No.',

    'text_enter_the_password'     => '请输入您的密码以便验证您的登录',
    'text_or_sign_in'             => '切换用户',
    'text_default_add_new_module' => '新增 :module',
    'text_default_list_module'    => '列表 :module',
    'text_default_help_password'  => '至少五个字符。如果没有修改密码请留空。',
    'text_default_help_upload'    => '支持的图片类型 : JPG, JPEG, PNG, GIF, BMP',
    'text_default_help_number'    => '请输入数字',
    'text_default_help_email'     => '请输入一个有效的邮箱',
    'text_default_help_text'      => '请输入字母',
    'text_default_help_url'       => '请输入一个有效的地址',
    'text_dashboard'              => '控制面板',
    'text_delete'                 => '删除',
    'text_prefix_option'          => '** 选择',
    'text_loading'                => '加载...',

    'message_after_logout'    => '下次再见!',
    'message_forgot_password' => '已将新密码发送到你的电子邮件,请到收件箱查看!',

    'page_not_found'      => '页面没有找到!',
    'page_not_found_text' => '没有搜索到你要找的页面。',
    'page_not_found_tips' => '* 请确认输入地址是否正确<br/>
                * 请确认字母大小写是否正确<br/>
                * 也许您正在寻找的页面已经被管理员删除<br/>
                * 你可以通过点击浏览器的后退按钮返回<br/>',

    'log_try_view'            => '请尝试在:module查看:name',
    'log_try_edit'            => '请尝试在:module编辑:name ',
    'log_try_add'             => '请尝试在:module添加数据',
    'log_try_add_save'        => '请尝试在:module新增:name',
    'log_try_delete'          => '请尝试在:module删除:name',
    'log_try_delete_selected' => '请尝试在:module删除选中项',
    'log_try_delete_image'    => '请尝试在:module删除:name的头像',
    'log_try_update'          => '请尝试在:module更新:name',
    'log_add'                 => '在:module新增:name',
    'log_update'              => '在:module更新:name',
    'log_delete'              => '在:module删除:name',
    'log_delete_image'        => '在:module删除:name的头像',
    'log_login'               => ':email 登录并附带 :ip',
    'log_forgot'              => '有人使用 :ip 为 :email申请密码',
    'log_logout'              => ':email 退出',

    'alert_delete_selected'         => '你确认批量删除吗 ?',
    'alert_delete_selected_success' => '删除选中项 !',
    'alert_bulk_action_button'      => '你确认',    
    'alert_action'                  => '你 :action 成功 !',
    'alert_add_data_success'        => '新增成功 !',
    'alert_add_data_failed'         => '保存失败 !',
    'alert_update_data_success'     => '更新完成 !',
    'alert_update_data_failed'      => '更新失败',
    'alert_delete_data_success'     => '删除成功 !',
    'alert_want_to_logout'          => '退出登录?',
    'alert_warning'                 => "哎呀",
    'alert_danger'                  => '不妙 ....',
    'alert_success'                 => '哇, 干的不错...',
    'alert_info'                    => '通知',
    'alert_primary'                 => '通知',
    'alert_session_expired'         => '会话过期,请重新登录!',
    'alert_password_wrong'          => '对不起,你的密码是错误的!',
    'alert_required'                => '请确认正确填写所有必填字段',
    'alert_error_ajax'              => '抱歉，确实有问题，我们会尽快修复它!',
    'alert_validation_error'        => '请正确填写: :error',

    'add_data_page_title'    => ':module新增',
    'edit_data_page_title'   => ':module编辑',
    'detail_data_page_title' => ':module详情',

    'default_module_description' => '列表',

    'delete_description_confirm' => "删除之后将无法恢复!",
    'delete_title_confirm'       => "确认删除吗 ?",


    'action_show_data'       => '查看',
    'action_add_data'        => '新增',
    'action_delete_selected' => '删除',

    'action_label'       => '操作',
    'action_detail_data' => '详情',
    'action_edit_data'   => '编辑',
    'action_delete_data' => '删除',


    'button_cancel'          => '撤销',
    'button_add'             => '新增',
    'button_edit'            => '编辑',
    'button_back'            => '返回',
    'button_save'            => '保存',
    'button_save_more'       => '保存并继续',
    'button_import'          => '导入',
    'button_export'          => '导出',
    'button_filter'          => '筛选',
    'button_close'           => '关闭',
    'button_submit'          => '提交',
    'button_logout'          => '退出',
    'button_sign_in'         => '登录',
    'button_selected_action' => '批量',
    'button_download_file'   => '下载',
    'button_reset'           => '重置',

    'export_dialog_title'            => "导出",
    'export_dialog_filename'         => '文件名',
    'export_dialog_help_filename'    => '支持自定义文件名',
    'export_dialog_maxdata'          => "最大行数",
    'export_dialog_help_maxdata'     => '每次只允许导出1~10万行数据',
    'export_dialog_columns'          => '标题字段',
    'export_dialog_format_export'    => '导出文件格式',
    'export_dialog_show_advanced'    => '显示高级',
    'export_dialog_page_size'        => '导出页面大小',
    'export_dialog_set_default'      => '设置为默认的页面大小',
    'export_dialog_page_orientation' => '导出页面方向',

    'import_page_title'         => '导入:module',
    'dashboard_default_text'    => '欢迎来到:appname的控制面板',
    'form_back_to_list'         => '返回:module列表',
    'not_logged_in'             => '你还没有登录!',
    'menu_navigation'           => "导航",
    'table_data_not_found'      => "没有有效数据",
    "notice_delete_file_upload" => "* 如果你想上传新的文件，请先删除已上传文件！",
    "file_broken"               => "文件好像已经被损坏 !. 点击删除并重新上传.",

    'denied_access' => '对不起，你没有访问权限!',
    'denied_update' => '对不起，你没有更新权限!',
    'denied_create' => '对不起，你没有新增权限!',
    'denied_delete' => '对不起，你没有删除权限!',

    'user_image'           => '头像',
    'online'               => '在线',
    'controller_route_404' => '页面不存在',
    'home'                 => '首页',
    'Notificactions'	  => 'Notifications',
    'Privileges'    	  => 'Privileges',
    'Privileges_Roles'    => '角色权限',
    'Add_New_Privilege'   => '新增角色',
    'List_Privilege'      => '角色列表',
    'add_user'            => '新增用户',
    'List_users'          => '用户列表',
    'Menu_Management'     => '菜单管理',
    'Add_New_Setting'     => '新增配置',
    'Add_New_Module'      => '新增模块',
    'List_Module'         => '模块列表',
    'Add_New_Statistic'   => '新增统计视图',
    'List_Statistic'      => '统计视图列表',
    'Add_New_API'         => '新增API',
    'API_Generator'       => 'API生成器',
    'Statistic_Builder'   => '统计视图',
    'Module_Generator'    => '模块生成器',
    'settings'            => '配置管理',
    'Users_Management'    => '用户管理',
    'list_API'            => 'API列表',
    'Generate_Screet_Key' => '生成密钥',
    'Add_New_Email'       => '新建邮件',
    'List_Email_Template' => '邮件模块列表',
    'Email_Templates'     => '邮件模块',
    'Log_User_Access'     => '操作记录',
    'SUPERADMIN'          => '管理面板',

    'click_here' => '点这里',

    /*
     * this is for html direction to use in html and css classes like :
     * pull-left , pull-right , text-right ...
     * to make it easy to use the the view for rtl langs .
     * unless your language use right-to-left direction , you should keep it as it is :
     */
    'right'      => 'right',
    'left'       => 'left',

    'all_rights_reserved' => 'All Rights Reserved',
    'copyright'           => 'Copyright',
    'powered_by'          => 'Powered by',

    'notification_you_have'     => '你收到',
    'notification_notification' => '通知',
    'notification_new'          => '你收到一条新的通知!',

    'login_register_style'         => '登录风格',
    'email_setting'                => '邮箱设置',
    'application_setting'          => '应用设置',

    // table filter & sort 
    'filter_select_operator_type'  => '选择',
    'filter_ascending'             => '顺序',
    'filter_descending'            => '倒序',
    'filter_equal_to'              => '等于',
    'filter_like'                  => '模糊查询',
    'filter_not_like'              => '模糊排除',
    'filter_greater_than_or_equal' => '大于等于',
    'filter_less_than_or_equal'    => '小于等于',
    'filter_less_than'             => '小于',
    'filter_greater_than'          => '大于',
    'filter_not_equal_to'          => '不等于',
    'filter_in'                    => '包含',
    'filter_not_in'                => '不包含',
    'filter_between'               => '日期或数字区间',
    'filter_sort_ascending'        => '顺序排列',
    'filter_sort_descending'       => '倒序排列',
    'filter_eg'                    => '例如',
    'filter_lorem_ipsum'           => 'Lorem ipsum',
    'filter_lorem_ipsum_dolor_sit' => ' Lorem,Ipsum,Dolor Sit',
    'filter_search'                => '查询',
    'filter_from'                  => '从',
    'filter_to'                    => '到',

    // confirmation
    'confirmation_yes'             => '是!',
    'confirmation_no'              => '否',

    //filemanager
    'chose_an_image'               => '选择一张图片 ',
    'chose_an_file'                => '选择一个文件 ',
    
    //action confirmation
    'confirmation_title'            => '确认',
    'confirmation_text'             => '你确认执行此操作吗?',
    'confirmButtonText'             => '是',

    
    // privilege
    'privileges_name'               =>'角色名称',
    'privileges_super_admin'        =>'超级管理员',
    'privileges_standart_user'      =>'普通用户',
    'privileges_ID'                 =>'角色编号',
    'set_as_superadmin'             =>'设置为超级管理员',
    'chose_theme_color_select'      =>'** 选择主题',
    'chose_theme_color'             =>' 主题颜色',
    'privileges_configuration'      =>'权限配置',
    'privileges_module_list_no'     =>'编号',
    'privileges_module_list_mod_names'=>'模块名称',
    'privileges_module_list_view'   =>'查看',
    'privileges_module_list_create' =>'可写',
    'privileges_module_list_read'   =>'只读',
    'privileges_module_list_update' =>'更新',
    'privileges_module_list_delete' =>'删除',

    //datamodal 
    'datamodal_select'=>'选择',
    'datamodal_search_and_enter'=>'查询并进入...',
    'datamodal_enter_to_search'=>'进入查询',
    'datamodal_browse_data'=>'浏览数据' ,
    
];
